package com.google.android.gms.location.places;

import android.os.Parcel;
import com.google.android.gms.common.internal.safeparcel.SafeParcelable;
import com.google.android.gms.internal.kn;

public final class PlaceType implements SafeParcelable {
    public static final PlaceType ACCOUNTING;
    public static final PlaceType ADMINISTRATIVE_AREA_LEVEL_1;
    public static final PlaceType ADMINISTRATIVE_AREA_LEVEL_2;
    public static final PlaceType ADMINISTRATIVE_AREA_LEVEL_3;
    public static final PlaceType AIRPORT;
    public static final PlaceType AMUSEMENT_PARK;
    public static final PlaceType AQUARIUM;
    public static final PlaceType ART_GALLERY;
    public static final PlaceType ATM;
    public static final PlaceType BAKERY;
    public static final PlaceType BANK;
    public static final PlaceType BAR;
    public static final PlaceType BEAUTY_SALON;
    public static final PlaceType BICYCLE_STORE;
    public static final PlaceType BOOK_STORE;
    public static final PlaceType BOWLING_ALLEY;
    public static final PlaceType BUS_STATION;
    public static final PlaceType CAFE;
    public static final PlaceType CAMPGROUND;
    public static final PlaceType CAR_DEALER;
    public static final PlaceType CAR_RENTAL;
    public static final PlaceType CAR_REPAIR;
    public static final PlaceType CAR_WASH;
    public static final PlaceType CASINO;
    public static final PlaceType CEMETERY;
    public static final PlaceType CHURCH;
    public static final PlaceType CITY_HALL;
    public static final PlaceType CLOTHING_STORE;
    public static final PlaceType COLLOQUIAL_AREA;
    public static final PlaceType CONVENIENCE_STORE;
    public static final PlaceType COUNTRY;
    public static final PlaceType COURTHOUSE;
    public static final h CREATOR;
    public static final PlaceType DENTIST;
    public static final PlaceType DEPARTMENT_STORE;
    public static final PlaceType DOCTOR;
    public static final PlaceType ELECTRICIAN;
    public static final PlaceType ELECTRONICS_STORE;
    public static final PlaceType EMBASSY;
    public static final PlaceType ESTABLISHMENT;
    public static final PlaceType FINANCE;
    public static final PlaceType FIRE_STATION;
    public static final PlaceType FLOOR;
    public static final PlaceType FLORIST;
    public static final PlaceType FOOD;
    public static final PlaceType FUNERAL_HOME;
    public static final PlaceType FURNITURE_STORE;
    public static final PlaceType GAS_STATION;
    public static final PlaceType GENERAL_CONTRACTOR;
    public static final PlaceType GEOCODE;
    public static final PlaceType GROCERY_OR_SUPERMARKET;
    public static final PlaceType GYM;
    public static final PlaceType HAIR_CARE;
    public static final PlaceType HARDWARE_STORE;
    public static final PlaceType HEALTH;
    public static final PlaceType HINDU_TEMPLE;
    public static final PlaceType HOME_GOODS_STORE;
    public static final PlaceType HOSPITAL;
    public static final PlaceType INSURANCE_AGENCY;
    public static final PlaceType INTERSECTION;
    public static final PlaceType JEWELRY_STORE;
    public static final PlaceType LAUNDRY;
    public static final PlaceType LAWYER;
    public static final PlaceType LIBRARY;
    public static final PlaceType LIQUOR_STORE;
    public static final PlaceType LOCALITY;
    public static final PlaceType LOCAL_GOVERNMENT_OFFICE;
    public static final PlaceType LOCKSMITH;
    public static final PlaceType LODGING;
    public static final PlaceType MEAL_DELIVERY;
    public static final PlaceType MEAL_TAKEAWAY;
    public static final PlaceType MOSQUE;
    public static final PlaceType MOVIE_RENTAL;
    public static final PlaceType MOVIE_THEATER;
    public static final PlaceType MOVING_COMPANY;
    public static final PlaceType MUSEUM;
    public static final PlaceType NATURAL_FEATURE;
    public static final PlaceType NEIGHBORHOOD;
    public static final PlaceType NIGHT_CLUB;
    public static final PlaceType OTHER;
    public static final PlaceType PAINTER;
    public static final PlaceType PARK;
    public static final PlaceType PARKING;
    public static final PlaceType PET_STORE;
    public static final PlaceType PHARMACY;
    public static final PlaceType PHYSIOTHERAPIST;
    public static final PlaceType PLACE_OF_WORSHIP;
    public static final PlaceType PLUMBER;
    public static final PlaceType POINT_OF_INTEREST;
    public static final PlaceType POLICE;
    public static final PlaceType POLITICAL;
    public static final PlaceType POSTAL_CODE;
    public static final PlaceType POSTAL_CODE_PREFIX;
    public static final PlaceType POSTAL_TOWN;
    public static final PlaceType POST_BOX;
    public static final PlaceType POST_OFFICE;
    public static final PlaceType PREMISE;
    public static final PlaceType REAL_ESTATE_AGENCY;
    public static final PlaceType RESTAURANT;
    public static final PlaceType ROOFING_CONTRACTOR;
    public static final PlaceType ROOM;
    public static final PlaceType ROUTE;
    public static final PlaceType RV_PARK;
    public static final PlaceType SCHOOL;
    public static final PlaceType SHOE_STORE;
    public static final PlaceType SHOPPING_MALL;
    public static final PlaceType SPA;
    public static final PlaceType STADIUM;
    public static final PlaceType STORAGE;
    public static final PlaceType STORE;
    public static final PlaceType STREET_ADDRESS;
    public static final PlaceType SUBLOCALITY;
    public static final PlaceType SUBLOCALITY_LEVEL_1;
    public static final PlaceType SUBLOCALITY_LEVEL_2;
    public static final PlaceType SUBLOCALITY_LEVEL_3;
    public static final PlaceType SUBLOCALITY_LEVEL_4;
    public static final PlaceType SUBLOCALITY_LEVEL_5;
    public static final PlaceType SUBPREMISE;
    public static final PlaceType SUBWAY_STATION;
    public static final PlaceType SYNAGOGUE;
    public static final PlaceType TAXI_STAND;
    public static final PlaceType TRAIN_STATION;
    public static final PlaceType TRANSIT_STATION;
    public static final PlaceType TRAVEL_AGENCY;
    public static final PlaceType UNIVERSITY;
    public static final PlaceType VETERINARY_CARE;
    public static final PlaceType ZOO;
    final int mVersionCode;
    final String vc;

    static {
        ACCOUNTING = create("accounting");
        AIRPORT = create("airport");
        AMUSEMENT_PARK = create("amusement_park");
        AQUARIUM = create("aquarium");
        ART_GALLERY = create("art_gallery");
        ATM = create("atm");
        BAKERY = create("bakery");
        BANK = create("bank");
        BAR = create("bar");
        BEAUTY_SALON = create("beauty_salon");
        BICYCLE_STORE = create("bicycle_store");
        BOOK_STORE = create("book_store");
        BOWLING_ALLEY = create("bowling_alley");
        BUS_STATION = create("bus_station");
        CAFE = create("cafe");
        CAMPGROUND = create("campground");
        CAR_DEALER = create("car_dealer");
        CAR_RENTAL = create("car_rental");
        CAR_REPAIR = create("car_repair");
        CAR_WASH = create("car_wash");
        CASINO = create("casino");
        CEMETERY = create("cemetery");
        CHURCH = create("church");
        CITY_HALL = create("city_hall");
        CLOTHING_STORE = create("clothing_store");
        CONVENIENCE_STORE = create("convenience_store");
        COURTHOUSE = create("courthouse");
        DENTIST = create("dentist");
        DEPARTMENT_STORE = create("department_store");
        DOCTOR = create("doctor");
        ELECTRICIAN = create("electrician");
        ELECTRONICS_STORE = create("electronics_store");
        EMBASSY = create("embassy");
        ESTABLISHMENT = create("establishment");
        FINANCE = create("finance");
        FIRE_STATION = create("fire_station");
        FLORIST = create("florist");
        FOOD = create("food");
        FUNERAL_HOME = create("funeral_home");
        FURNITURE_STORE = create("furniture_store");
        GAS_STATION = create("gas_station");
        GENERAL_CONTRACTOR = create("general_contractor");
        GROCERY_OR_SUPERMARKET = create("grocery_or_supermarket");
        GYM = create("gym");
        HAIR_CARE = create("hair_care");
        HARDWARE_STORE = create("hardware_store");
        HEALTH = create("health");
        HINDU_TEMPLE = create("hindu_temple");
        HOME_GOODS_STORE = create("home_goods_store");
        HOSPITAL = create("hospital");
        INSURANCE_AGENCY = create("insurance_agency");
        JEWELRY_STORE = create("jewelry_store");
        LAUNDRY = create("laundry");
        LAWYER = create("lawyer");
        LIBRARY = create("library");
        LIQUOR_STORE = create("liquor_store");
        LOCAL_GOVERNMENT_OFFICE = create("local_government_office");
        LOCKSMITH = create("locksmith");
        LODGING = create("lodging");
        MEAL_DELIVERY = create("meal_delivery");
        MEAL_TAKEAWAY = create("meal_takeaway");
        MOSQUE = create("mosque");
        MOVIE_RENTAL = create("movie_rental");
        MOVIE_THEATER = create("movie_theater");
        MOVING_COMPANY = create("moving_company");
        MUSEUM = create("museum");
        NIGHT_CLUB = create("night_club");
        PAINTER = create("painter");
        PARK = create("park");
        PARKING = create("parking");
        PET_STORE = create("pet_store");
        PHARMACY = create("pharmacy");
        PHYSIOTHERAPIST = create("physiotherapist");
        PLACE_OF_WORSHIP = create("place_of_worship");
        PLUMBER = create("plumber");
        POLICE = create("police");
        POST_OFFICE = create("post_office");
        REAL_ESTATE_AGENCY = create("real_estate_agency");
        RESTAURANT = create("restaurant");
        ROOFING_CONTRACTOR = create("roofing_contractor");
        RV_PARK = create("rv_park");
        SCHOOL = create("school");
        SHOE_STORE = create("shoe_store");
        SHOPPING_MALL = create("shopping_mall");
        SPA = create("spa");
        STADIUM = create("stadium");
        STORAGE = create("storage");
        STORE = create("store");
        SUBWAY_STATION = create("subway_station");
        SYNAGOGUE = create("synagogue");
        TAXI_STAND = create("taxi_stand");
        TRAIN_STATION = create("train_station");
        TRAVEL_AGENCY = create("travel_agency");
        UNIVERSITY = create("university");
        VETERINARY_CARE = create("veterinary_care");
        ZOO = create("zoo");
        ADMINISTRATIVE_AREA_LEVEL_1 = create("administrative_area_level_1");
        ADMINISTRATIVE_AREA_LEVEL_2 = create("administrative_area_level_2");
        ADMINISTRATIVE_AREA_LEVEL_3 = create("administrative_area_level_3");
        COLLOQUIAL_AREA = create("colloquial_area");
        COUNTRY = create("country");
        FLOOR = create("floor");
        GEOCODE = create("geocode");
        INTERSECTION = create("intersection");
        LOCALITY = create("locality");
        NATURAL_FEATURE = create("natural_feature");
        NEIGHBORHOOD = create("neighborhood");
        POLITICAL = create("political");
        POINT_OF_INTEREST = create("point_of_interest");
        POST_BOX = create("post_box");
        POSTAL_CODE = create("postal_code");
        POSTAL_CODE_PREFIX = create("postal_code_prefix");
        POSTAL_TOWN = create("postal_town");
        PREMISE = create("premise");
        ROOM = create("room");
        ROUTE = create("route");
        STREET_ADDRESS = create("street_address");
        SUBLOCALITY = create("sublocality");
        SUBLOCALITY_LEVEL_1 = create("sublocality_level_1");
        SUBLOCALITY_LEVEL_2 = create("sublocality_level_2");
        SUBLOCALITY_LEVEL_3 = create("sublocality_level_3");
        SUBLOCALITY_LEVEL_4 = create("sublocality_level_4");
        SUBLOCALITY_LEVEL_5 = create("sublocality_level_5");
        SUBPREMISE = create("subpremise");
        TRANSIT_STATION = create("transit_station");
        OTHER = create("other");
        CREATOR = new h();
    }

    PlaceType(int versionCode, String type) {
        kn.bk(type);
        this.mVersionCode = versionCode;
        this.vc = type;
    }

    public static PlaceType create(String type) {
        return new PlaceType(0, type);
    }

    public int describeContents() {
        h hVar = CREATOR;
        return 0;
    }

    public boolean equals(Object o) {
        return (o instanceof PlaceType) && this.vc.equals(((PlaceType) o).vc);
    }

    public int hashCode() {
        return this.vc.hashCode();
    }

    public String toString() {
        return this.vc;
    }

    public void writeToParcel(Parcel parcel, int flags) {
        h hVar = CREATOR;
        h.a(this, parcel, flags);
    }
}
