package com.xiaomi.passport;

import com.xiaomi.accountsdk.account.XMPassport;

public class Constants {
    public static final String ACCOUNT_AVATAR_FILE_NAME = "acc_avatar_file_name";
    public static final String ACCOUNT_AVATAR_URL = "acc_avatar_url";
    public static final String ACCOUNT_NICK_NAME = "acc_nick_name";
    public static final String ACCOUNT_RANDOM_DEVICE_ID = "acc_random_device_id";
    public static final String ACCOUNT_RANDOM_SIM_ID = "acc_random_sim_id";
    public static final String ACCOUNT_TYPE = "com.xiaomi";
    public static final String ACCOUNT_USER_EMAIL = "acc_user_email";
    public static final String ACCOUNT_USER_NAME = "acc_user_name";
    public static final String ACCOUNT_USER_PHONE = "acc_user_phone";
    public static final String ACTION_ACCOUNT_REG_FAILED = "com.xiaomi.account.action.XIAOMI_ACCOUNT_REG_FAILED";
    public static final String ACTION_ACCOUNT_UNACTIVATED = "com.xiaomi.account.action.XIAOMI_ACCOUNT_UNACTIVATED";
    public static final String ACTION_AREA_CODE = "com.xiaomi.account.action.XIAOMI_ACCOUNT_AREA_CODE";
    public static final String ACTION_LOGIN = "com.xiaomi.account.action.XIAOMI_ACCOUNT_LOGIN";
    public static final String ACTION_QUICK_LOGIN = "com.xiaomi.account.action.XIAOMI_ACCOUNT_QUICK_LOGIN";
    public static final String ACTION_REG = "com.xiaomi.account.action.XIAOMI_ACCOUNT_REG";
    public static final String ACTION_VIEW_LICENSE = "com.xiaomi.account.action.VIEW_LICENSE";
    public static final String ACTION_WELCOME = "com.xiaomi.account.action.XIAOMI_ACCOUNT_WELCOME";
    public static final String AVATAR_FILE_NAME = "xiaomi_user_avatar_";
    public static final boolean DEBUG = true;
    public static final boolean ENABLE_ANALYTICS = true;
    public static final String EXTRA_ACCOUNT = "extra_account";
    public static final String EXTRA_ACTIVATED_IMSI = "extra_activated_imsi";
    public static final String EXTRA_ADD_ACCOUNT_PROMPT = "extra_add_account_prompt";
    public static final String EXTRA_AUTO_LOGIN = "extra_auto_login";
    public static final String EXTRA_AUTO_LOGIN_NAME = "extra_auto_login_name";
    public static final String EXTRA_AUTO_LOGIN_PWD = "extra_auto_login_pwd";
    public static final String EXTRA_BIND_SNS_TYPE = "extra_bind_sns_type";
    public static final String EXTRA_BUILD_REGION_INFO = "extra_build_region_info";
    public static final String EXTRA_CALLBACK = "extra_callback";
    public static final String EXTRA_CAPTCHA_URL = "extra_captcha_url";
    public static final String EXTRA_CLEAR_WHEN_RESET = "extra_clear_when_reset";
    public static final String EXTRA_DISABLE_BACK_KEY = "extra_disable_back_key";
    public static final String EXTRA_ERROR = "extra_error";
    public static final String EXTRA_FIND_PASSWORD_ON_PC = "extra_find_pwd_on_pc";
    public static final String EXTRA_FROM_BACK_NAVIGATION = "flag_from_back_nav";
    public static final String EXTRA_QS = "extra_qs";
    public static final String EXTRA_RESET_COUNT = "extra_reset_count";
    public static final String EXTRA_SERVICE_URL = "extra_service_url";
    public static final String EXTRA_SHOW_ACCOUNT_SETTINGS = "show_account_settings";
    public static final String EXTRA_SHOW_SKIP_LOGIN = "extra_show_skip_login";
    public static final String EXTRA_SHOW_SYNC_SETTINGS = "show_sync_settings";
    public static final String EXTRA_SIGN = "extra_sign";
    public static final String EXTRA_STEP1_TOKEN = "extra_step1_token";
    public static final String EXTRA_TITLE = "extra_title";
    public static final String EXTRA_UPLINK = "extra_uplink";
    public static final String EXTRA_USER_ID = "extra_user_id";
    public static final String EXTRA_USER_NAME = "extra_username";
    public static final String EXTRA_VERIFY_ONLY = "verify_only";
    public static final String EXTRA_XIAOMI_ACCOUNT_NAME = "user_name";
    public static final String FALSE = "false";
    public static final String KEY_CAPTCHA_CODE = "captcha_code";
    public static final String KEY_CAPTCHA_ICK = "captcha_ick";
    public static final String KEY_CAPTCHA_URL = "captcha_url";
    public static final String KEY_DATA = "data";
    public static final String KEY_EMAIL = "email";
    public static final String KEY_ENCRYPTED_USER_ID = "encrypted_user_id";
    public static final String KEY_RESULT = "result";
    public static final String KEY_SERVICE_ID = "service_id";
    public static final String KEY_TITLE = "title";
    public static final String KEY_VCODE = "vcode";
    public static final String LAST_ACTIVATE_TIME = "last_activate_time";
    public static final String LICENSE_TYPE = "license_type";
    public static final String MASK = "*********";
    public static final int NOTIF_ACTIVATE_ACCOUNT_ID = 1;
    public static final int NOTIF_ACTIVATE_PHONE_ID_START = 2;
    public static final String PASSPORT_API_SID = "passportapi";
    public static final String PASSWORD_RECOVERY_URL;
    public static final String PREF_CURRENT_GATEWAY_INDEX = "pref_current_gateway_index_";
    public static final String REG_SIM_ID_PREFIX = "reg_sim_id_";
    public static final String REG_TYPE_EMAIL = "reg_email";
    public static final String REG_TYPE_OTHER_PHONE = "reg_other_phone";
    public static final String REG_TYPE_PHONE_NUMBER = "reg_sms";
    public static final long RESEND_ACTIVATE_EMAIL_INTERVAL = 30000;
    public static final int RESULT_CODE_NET_ERROR = 3;
    public static final int RESULT_FIELD_INVALID_FORMAT = 2;
    public static final int RESULT_FIELD_NOT_USABLE = 1;
    public static final long SMS_GW_EXPIRE_TIME = 0;
    public static final String SPLITER_SMS_GATEWAY = ",";
    public static final String SUB_SYNC_PREFIX = "sub_sync_";
    public static final String TRUE = "true";

    static {
        PASSWORD_RECOVERY_URL = XMPassport.URL_ACCOUNT_BASE + "/forgetPassword";
    }
}
