package com.google.android.finsky.config;

import com.google.android.play.utils.config.GservicesValue;

public class G {
    public static final String[] GSERVICES_KEY_PREFIXES;
    public static final GservicesValue<String> additionalExperiments;
    public static GservicesValue<Boolean> analyticsEnabled;
    public static GservicesValue<Boolean> antiMalwareActivityEnabled;
    public static final GservicesValue<Integer> appRestoreAppIconMaxAttempts;
    public static final GservicesValue<Integer> appRestoreDownloadMaxAttempts;
    public static final GservicesValue<Long> appRestoreFailsafeMs;
    public static final GservicesValue<Integer> appRestoreFetchListMaxAttempts;
    public static final GservicesValue<Long> appRestoreHoldoffMs;
    public static final GservicesValue<String> appRestoreHttpStatusBlacklist;
    public static final GservicesValue<Long> appRestoreRetryDownloadHoldoffHighPriorityMs;
    public static final GservicesValue<Long> appRestoreRetryDownloadHoldoffMs;
    public static final GservicesValue<Long> appRestoreRetryFetchListHoldoffMs;
    public static GservicesValue<String> appsWidgetUrl;
    public static final GservicesValue<Long> autoUpdateDeliveryHoldoffMs;
    public static final GservicesValue<Integer> autoUpdateDialogFirstBackoffDays;
    public static final GservicesValue<Integer> autoUpdateDialogSecondBackoffDays;
    public static final GservicesValue<Integer> autoUpdateDialogSubsequentBackoffDays;
    public static final GservicesValue<Boolean> autoUpdateExcludeForegroundServices;
    public static final GservicesValue<Boolean> autoUpdateExcludeRunningPackagesPre;
    public static final GservicesValue<Long> autoUpdateJobSchedulerGearheadDelayMs;
    public static final GservicesValue<Long> autoUpdateJobSchedulerGearheadTimeoutMs;
    public static final GservicesValue<Long> autoUpdateJobSchedulerTimeoutMs;
    public static final GservicesValue<Long> autoUpdateWifiCheckIntervalMs;
    public static GservicesValue<String> booksWidgetUrl;
    public static GservicesValue<String> checkoutPrivacyPolicyUrl;
    public static final GservicesValue<Integer> clientMutationCacheCirclesModelCacheSize;
    public static final GservicesValue<Boolean> consistencyTokenEnabled;
    public static GservicesValue<String> consumptionAppDataFilter;
    public static final GservicesValue<Long> consumptionAppImageTimeoutMs;
    public static final GservicesValue<Long> consumptionAppTimeoutMs;
    public static GservicesValue<String> contentFilterInfoUrl;
    public static final GservicesValue<Long> continueUrlExpirationMs;
    public static final GservicesValue<Integer> corpusAwarenessThresholdBooks;
    public static final GservicesValue<Integer> corpusAwarenessThresholdMagazines;
    public static final GservicesValue<Integer> corpusAwarenessThresholdMovies;
    public static final GservicesValue<Integer> corpusAwarenessThresholdMusic;
    public static final GservicesValue<Long> dailyHygieneBootDelayMs;
    public static final GservicesValue<Boolean> dailyHygieneHoldoffDuringSelfUpdate;
    public static final GservicesValue<Long> dailyHygieneHoldoffIntervalMs;
    public static final GservicesValue<Long> dailyHygieneImmediateDelayMs;
    public static final GservicesValue<Integer> dailyHygieneImmediateRunVersionCodeHigh;
    public static final GservicesValue<Integer> dailyHygieneImmediateRunVersionCodeLow;
    public static final GservicesValue<Float> dailyHygieneInitialJitterFactor;
    public static final GservicesValue<Float> dailyHygieneJitterFactor;
    public static final GservicesValue<Long> dailyHygieneProvisionHoldoffMaxMs;
    public static final GservicesValue<Long> dailyHygieneRegularIntervalMs;
    public static final GservicesValue<Long> dailyHygieneRetryIntervalMs;
    public static final GservicesValue<Long> dcb2SetupDelayTosLoading;
    public static GservicesValue<Integer> dcb3PassphraseKeyVersion;
    public static GservicesValue<Boolean> dcb3PrepareSendDeviceRebooted;
    public static GservicesValue<Boolean> dcb3SetupWhileRoamingEnabled;
    public static GservicesValue<Integer> dcb3VerifyAssociationRetries;
    public static GservicesValue<Boolean> dcbDebugOptionsEnabled;
    public static GservicesValue<Boolean> debugAlwaysPromptForGaiaRecovery;
    public static GservicesValue<Boolean> debugLimitedUserState;
    public static GservicesValue<Boolean> debugOptionsEnabled;
    public static final GservicesValue<Integer> defaultPurchaseAuthentication;
    public static final GservicesValue<Long> deliveryDataExpirationMs;
    public static GservicesValue<Boolean> dfeLogsAdMobEnabled;
    public static final GservicesValue<Long> downloadBytesOverMobileMaximum;
    public static final GservicesValue<Long> downloadBytesOverMobileRecommended;
    public static final GservicesValue<Long> downloadExternalFileSizeMinBytes;
    public static final GservicesValue<Integer> downloadExternalFreeSpaceFactor;
    public static final GservicesValue<Long> downloadExternalFreeSpaceThresholdBytes;
    public static final GservicesValue<Integer> downloadFreeSpaceApkSizeFactor;
    public static final GservicesValue<Long> downloadFreeSpaceThresholdBytes;
    public static final GservicesValue<Integer> downloadPatchFreeSpaceFactor;
    public static final GservicesValue<Boolean> downloadSendBaseVersionCode;
    public static final GservicesValue<String> editPaymentMethodUrl;
    public static final GservicesValue<String> eduDevicePolicyApp;
    public static GservicesValue<Boolean> enableCorpusWidgets;
    public static final GservicesValue<Boolean> enableDcbReducedBillingAddress;
    public static final GservicesValue<Boolean> enableDetailsApi;
    public static GservicesValue<Boolean> enableGaiaRecovery;
    public static final GservicesValue<Boolean> enablePeopleSuggestWidget;
    public static GservicesValue<Boolean> enablePlayLogs;
    public static GservicesValue<Boolean> enableRemoveAppsFromLibrary;
    public static GservicesValue<Boolean> enableReviewComments;
    public static GservicesValue<Boolean> enableSensitiveLogging;
    public static final GservicesValue<Boolean> enableSessionStatsLog;
    public static final GservicesValue<Boolean> enableThirdPartyDetailsApi;
    public static final GservicesValue<Boolean> enableThirdPartyDirectPurchases;
    public static final GservicesValue<Boolean> enableThirdPartyInlineAppInstalls;
    public static final GservicesValue<Long> externalReferrerLifespanMs;
    public static final GservicesValue<Integer> firstNewsstandAppVersion;
    public static GservicesValue<Boolean> forcePostPurchaseCrossSell;
    public static final GservicesValue<Long> gaiaAuthValidityMs;
    public static final GservicesValue<String> gaiaOptOutLearnMoreLink;
    public static GservicesValue<String> gamesBrowseUrl;
    public static final GservicesValue<String> gelPackageName;
    public static final GservicesValue<Boolean> gmsCoreAutoUpdateEnabled;
    public static GservicesValue<Boolean> gtvNavigationalSuggestEnabled;
    public static final GservicesValue<Long> hasFopCacheTimeoutMs;
    public static final GservicesValue<String> helpCenterBackgroundDataUrl;
    public static final GservicesValue<Boolean> iabV3FirstPartyApiEnabled;
    public static final GservicesValue<Boolean> iabV3FirstPartyApiUnrestrictedAccess;
    public static GservicesValue<Integer> iabV3MaxPurchasesInResponse;
    public static GservicesValue<Long> iabV3NetworkTimeoutMs;
    public static GservicesValue<Integer> iabV3SkuDetailsMaxSize;
    public static final GservicesValue<Boolean> iabV3SubscriptionsEnabled;
    public static GservicesValue<Integer> imageCacheSizeMb;
    public static final GservicesValue<Integer> initializeBillingDelayMs;
    public static final GservicesValue<Long> instrumentCheckLifetimeMs;
    public static final GservicesValue<Boolean> launchUrlsEnabled;
    public static GservicesValue<String> legalNoticeMenuTitleOverride;
    public static GservicesValue<String> legalNoticeMenuUrl;
    public static final GservicesValue<Integer> libraryReplicatorRescheduleDelayMs;
    public static final GservicesValue<Long> lightPurchaseAutoDismissMs;
    public static final GservicesValue<Boolean> lightPurchaseOptimisticProvisioning;
    public static final GservicesValue<Boolean> logBillingEventsEnabled;
    public static final GservicesValue<Boolean> logInlineAppInstallReferrerEnabled;
    public static GservicesValue<Integer> logsDispatchIntervalSeconds;
    public static GservicesValue<Integer> mainCacheSizeMb;
    public static final GservicesValue<Integer> maxAutoUpdateDialogShownCount;
    public static GservicesValue<Integer> maxLogQueueSizeBeforeFlush;
    public static final GservicesValue<Integer> minimumMusicVersionCode;
    public static final GservicesValue<Integer> minimumNumberOfRecs;
    public static final GservicesValue<Integer> minimumVideosVersionCodeHoneycombPlus;
    public static final GservicesValue<Integer> minimumVideosVersionCodePreHoneycomb;
    public static GservicesValue<String> moviesWidgetUrl;
    public static final GservicesValue<String> musicAllAccessSignUpIntentUrl;
    public static final GservicesValue<String> musicAllAccessSubscriptionBackendDocid;
    public static final GservicesValue<String> musicAppSubscriptionBackendDocidBlacklist;
    public static final GservicesValue<Boolean> musicAppSubscriptionResignupEnabled;
    public static final GservicesValue<String> musicDmcaReportLink;
    public static GservicesValue<String> musicWidgetUrl;
    public static final GservicesValue<String> myLibraryWidgeMidtermScores;
    public static final GservicesValue<Boolean> myLibraryWidgetAlwaysIncludeMostRecentBackend;
    public static final GservicesValue<String> myLibraryWidgetBackgroundImageLocation;
    public static final GservicesValue<String> myLibraryWidgetHasContentScoreMap;
    public static final GservicesValue<Float> myLibraryWidgetImportantContributionFraction;
    public static final GservicesValue<Long> myLibraryWidgetInteractionClusterMs;
    public static final GservicesValue<Long> myLibraryWidgetMidtermDurationMs;
    public static final GservicesValue<Float> myLibraryWidgetShorttermDecay;
    public static final GservicesValue<Long> myLibraryWidgetShorttermDurationMs;
    public static final GservicesValue<String> myLibraryWidgetShorttermScores;
    public static final GservicesValue<Integer> nlpCleanupConfigurationId;
    public static final GservicesValue<String> nlpCleanupCookieName;
    public static final GservicesValue<String> nlpCleanupCookieNameTestKeys;
    public static final GservicesValue<String> nlpCleanupCookieValue;
    public static final GservicesValue<String> nlpCleanupCookieValueTestKeys;
    public static final GservicesValue<Boolean> nlpCleanupDowngradeFlag;
    public static final GservicesValue<String> nlpCleanupExpectedSignature;
    public static final GservicesValue<String> nlpCleanupExpectedSignatureTestKeys;
    public static final GservicesValue<Integer> nlpCleanupFlagsMask;
    public static final GservicesValue<Integer> nlpCleanupFlagsSet;
    public static final GservicesValue<Boolean> nlpCleanupLogCommonStatuses;
    public static final GservicesValue<Integer> nlpCleanupNlpVersionMax;
    public static final GservicesValue<Integer> nlpCleanupNlpVersionMin;
    public static final GservicesValue<Integer> nlpCleanupSdkVersionMax;
    public static final GservicesValue<Integer> nlpCleanupSdkVersionMin;
    public static final GservicesValue<String> nlpCleanupUrl;
    public static final GservicesValue<String> nlpCleanupUrlTestKeys;
    public static final GservicesValue<String> nlpPackageName;
    public static final GservicesValue<Integer> nlpReinstallSdkVersionMax;
    public static final GservicesValue<Integer> nlpReinstallSdkVersionMin;
    public static final GservicesValue<String> nlpSharedUserId;
    public static final GservicesValue<Long> outstandingNotificationTimeDelayMs;
    public static final GservicesValue<Integer> passwordMaxFailedAttempts;
    public static final GservicesValue<String> passwordRecoveryUrl;
    public static final GservicesValue<String> peoplePageWarmWelcomeButtonIconUrl;
    public static final GservicesValue<String> peoplePageWarmWelcomeGraphicUrl;
    public static final GservicesValue<String> permissionBucketsLearnMoreLink;
    public static final GservicesValue<Integer> placesApiBiasRadiusMeters;
    public static final GservicesValue<String> placesApiKey;
    public static GservicesValue<Long> platformAntiMalwareDialogDelayMs;
    public static GservicesValue<Boolean> platformAntiMalwareEnabled;
    public static final GservicesValue<String> playGamesDocId;
    public static final GservicesValue<Integer> playGamesGmsCoreMinVersion;
    public static final GservicesValue<Long> playGamesInstallSuggestionFirstBackoffMs;
    public static final GservicesValue<Integer> playGamesInstallSuggestionMaxShownCount;
    public static final GservicesValue<Boolean> playGamesInstallSuggestionOnlyWhenGameFeatures;
    public static final GservicesValue<Long> playGamesInstallSuggestionSubsequentBackoffMs;
    public static final GservicesValue<Long> playLogDelayBetweenUploadsMs;
    public static final GservicesValue<Long> playLogImpressionSettleTimeMs;
    public static final GservicesValue<Long> playLogMaxStorageSize;
    public static final GservicesValue<Long> playLogMinDelayBetweenUploadsMs;
    public static final GservicesValue<Long> playLogRecommendedFileSize;
    public static final GservicesValue<String> playLogServerUrl;
    public static final GservicesValue<Integer> positiveRateThreshold;
    public static final GservicesValue<Boolean> postPurchaseSharingEnabled;
    public static final GservicesValue<Boolean> prePurchaseSharingEnabled;
    public static final GservicesValue<Integer> preserveForwardLockApiMax;
    public static final GservicesValue<Integer> preserveForwardLockApiMin;
    public static final GservicesValue<String> promptForFopSnoozeScheduleM;
    public static GservicesValue<String> readBookUrl;
    public static final GservicesValue<Long> recentlyUpdatedWindowSizeMs;
    public static final GservicesValue<Long> recommendationTtlMs;
    public static final GservicesValue<Long> recommendationsFetchTimeoutMs;
    public static final GservicesValue<Integer> recommendationsWidgetFlipIntervalMs;
    public static GservicesValue<Integer> recsCacheSizeMb;
    public static GservicesValue<String> redeemTermsAndConditionsUrl;
    public static final GservicesValue<Boolean> reducedBillingAddressRequiresPhonenumber;
    public static final GservicesValue<String> resetPinUrl;
    public static final GservicesValue<Boolean> selectAddinstrumentByDefault;
    public static final GservicesValue<Long> setupWizardEarlyUpdateDeadlockMaxMs;
    public static final GservicesValue<Boolean> setupWizardEarlyUpdateEnable;
    public static GservicesValue<Boolean> setupWizardForceResizeForKeyboardInFullscreen;
    public static final GservicesValue<String> setupWizardPaymentHeaderGraphicUrl;
    public static final GservicesValue<String> setupWizardPaymentHeaderWideGraphicUrl;
    public static final GservicesValue<String> setupWizardRestoreFinalHoldHeaderLandscapeUrl;
    public static final GservicesValue<String> setupWizardRestoreFinalHoldHeaderTabletUrl;
    public static final GservicesValue<String> setupWizardRestoreFinalHoldHeaderUrl;
    public static final GservicesValue<Long> setupWizardRestoreFinalHoldLongMs;
    public static final GservicesValue<Long> setupWizardRestoreFinalHoldShortMs;
    public static final GservicesValue<String> setupWizardRestoreHeaderGraphicUrl;
    public static final GservicesValue<String> setupWizardRestoreWideHeaderGraphicUrl;
    public static final GservicesValue<Boolean> skipAutoUpdateCleanupClientVersionCheck;
    public static final GservicesValue<Boolean> subscriptionsEnabled;
    public static final GservicesValue<String> supportUrl;
    public static final GservicesValue<String> supportedAccountTypes;
    public static final GservicesValue<String> surveySiteIdOverallApp;
    public static final GservicesValue<String> surveySiteIdSearchResults;
    public static final GservicesValue<String> surveySiteIdSearchResultsControlGroup;
    public static final GservicesValue<Integer> tabskyMinVersion;
    public static final GservicesValue<Long> unsubmittedReviewLifespanMs;
    public static GservicesValue<Boolean> userCheckForSelfUpdateEnabled;
    public static final GservicesValue<String> vendingAddressServerUrl;
    public static final GservicesValue<Long> vendingAlarmExpirationTimeoutMs;
    public static final GservicesValue<Long> vendingAlarmMaxTimeoutMs;
    public static final GservicesValue<Long> vendingAlarmMinTimeoutMs;
    public static final GservicesValue<Boolean> vendingAlwaysSendConfig;
    public static GservicesValue<String> vendingAuthTokenType;
    public static final GservicesValue<Long> vendingBillingCountriesRefreshMs;
    public static final GservicesValue<Long> vendingCarrierCredentialsBufferMs;
    public static final GservicesValue<Long> vendingCarrierProvisioningRefreshFrequencyMs;
    public static final GservicesValue<Long> vendingCarrierProvisioningRetryMs;
    public static final GservicesValue<Boolean> vendingCarrierProvisioningUseTosVersion;
    public static final GservicesValue<Integer> vendingContentRating;
    public static final GservicesValue<String> vendingDcbConnectionType;
    public static final GservicesValue<Boolean> vendingDcbMmsFallback;
    public static final GservicesValue<Integer> vendingDcbPollTimeoutMs;
    public static final GservicesValue<String> vendingDcbProxyHost;
    public static final GservicesValue<Integer> vendingDcbProxyPort;
    public static final GservicesValue<Boolean> vendingHideContentRating;
    public static final GservicesValue<Integer> vendingRequestTimeoutMs;
    public static GservicesValue<String> vendingSecureAuthTokenType;
    public static GservicesValue<Float> verifyInstalledPackagesBackoffMultiplier;
    public static GservicesValue<Boolean> verifyInstalledPackagesEnabled;
    public static GservicesValue<Long> verifyInstalledPackagesMinimumWaitMs;
    public static GservicesValue<Integer> verifyInstalledPackagesNumRetries;
    public static GservicesValue<Integer> verifyInstalledPackagesTimeoutMs;
    public static GservicesValue<Boolean> verifyInstalledPlayPackagesEnabled;
    public static final GservicesValue<Integer> videoAppTrailerPlaybackMinVersion;
    public static final GservicesValue<Integer> volleyBufferPoolSizeKb;
    public static final GservicesValue<String> walletEscrowUrl;
    public static final GservicesValue<String> whitelistedPlacesApiCountries;

    static {
        GSERVICES_KEY_PREFIXES = new String[]{"android_id", "finsky.", "vending_", "logging_id2", "market_client_id"};
        mainCacheSizeMb = GservicesValue.value("finsky.main_cache_size_mb", Integer.valueOf(1));
        imageCacheSizeMb = GservicesValue.value("finsky.image_cache_size_mb", Integer.valueOf(4));
        recsCacheSizeMb = GservicesValue.value("finsky.recs_cache_size_mb", Integer.valueOf(5));
        debugOptionsEnabled = GservicesValue.value("finsky.debug_options_enabled", Boolean.valueOf(false));
        userCheckForSelfUpdateEnabled = GservicesValue.value("finsky.user_check_for_self_update_enabled", Boolean.valueOf(true));
        debugLimitedUserState = GservicesValue.value("finsky.debug_limited_user_state", Boolean.valueOf(false));
        debugAlwaysPromptForGaiaRecovery = GservicesValue.value("finsky.always_prompt_for_gaia_recovery", Boolean.valueOf(false));
        enableGaiaRecovery = GservicesValue.value("finsky.enable_gaia_recovery", Boolean.valueOf(true));
        gtvNavigationalSuggestEnabled = GservicesValue.value("finsky.gtv_navigational_suggestions_enabled", Boolean.valueOf(false));
        legalNoticeMenuTitleOverride = GservicesValue.value("finsky.extra_menu_item_title", "");
        legalNoticeMenuUrl = GservicesValue.value("finsky.extra_menu_item_url", "");
        gamesBrowseUrl = GservicesValue.value("finsky.games_browse_url", "home?c=3&cat=GAME");
        dfeLogsAdMobEnabled = GservicesValue.value("finsky.dfe_logs_admob_enabled", Boolean.valueOf(true));
        logsDispatchIntervalSeconds = GservicesValue.value("finsky.logs_dispatch_interval_seconds", Integer.valueOf(15));
        maxLogQueueSizeBeforeFlush = GservicesValue.value("finsky.maximum_log_queue_size", Integer.valueOf(40));
        vendingAuthTokenType = GservicesValue.value("vending.auth_token_type", "android");
        vendingSecureAuthTokenType = GservicesValue.value("vending.secure_auth_token_type", "androidsecure");
        checkoutPrivacyPolicyUrl = GservicesValue.value("finsky.checkout_privacy_policy_url", "https://wallet.google.com/files/privacy.html?hl=%lang%");
        redeemTermsAndConditionsUrl = GservicesValue.value("finsky.redeem_terms_and_conditions_url", "https://play.google.com/intl/%locale%/about/redeem-terms.html");
        enableCorpusWidgets = GservicesValue.value("finsky.enable_corpus_widgets", Boolean.valueOf(false));
        appsWidgetUrl = GservicesValue.value("finsky.widget_url", "promo?c=3");
        musicWidgetUrl = GservicesValue.value("finsky.music_widget_url", "promo?c=2");
        booksWidgetUrl = GservicesValue.value("finsky.books_widget_url", "promo?c=1");
        moviesWidgetUrl = GservicesValue.value("finsky.movies_widget_url", "promo?c=4");
        consumptionAppDataFilter = GservicesValue.value("finsky.consumption_app_data_filter", "");
        readBookUrl = GservicesValue.value("finsky.read_book_url", "http://books.google.com/ebooks/reader");
        contentFilterInfoUrl = GservicesValue.value("finsky.content_filter_info_url", "http://www.google.com/support/androidmarket/bin/answer.py?answer=1075738");
        analyticsEnabled = GservicesValue.value("finsky.analytics_enabled", Boolean.valueOf(true));
        walletEscrowUrl = GservicesValue.value("finsky.wallet_escrow_url", "https://wallet.google.com/dehEfe");
        musicDmcaReportLink = GservicesValue.value("finsky.music_dmca_report_link", "https://www.google.com/support/artists?p=DMCA");
        permissionBucketsLearnMoreLink = GservicesValue.value("finsky.permission_buckets_learn_more_link", "https://support.google.com/googleplay/?p=app_permissions");
        gaiaOptOutLearnMoreLink = GservicesValue.value("finsky.gaia_opt_out_learn_more_link", "http://support.google.com/googleplay/bin/answer.py?&answer=2889951");
        initializeBillingDelayMs = GservicesValue.value("finsky.initialize_billing_delay_ms", Integer.valueOf(10000));
        hasFopCacheTimeoutMs = GservicesValue.value("finsky.has_fop_cache_timeout_ms", Long.valueOf(604800000));
        promptForFopSnoozeScheduleM = GservicesValue.value("finsky.prompt_for_fop_snooze_schedule_m", "10080");
        logBillingEventsEnabled = GservicesValue.value("finsky.log_billing_events_enabled", Boolean.valueOf(true));
        enableSensitiveLogging = GservicesValue.value("finsky.enable_sensitive_logging", Boolean.valueOf(false));
        enablePlayLogs = GservicesValue.value("finsky.enable_playlog", Boolean.valueOf(true));
        forcePostPurchaseCrossSell = GservicesValue.value("finsky.force_post_purchase_cross_sell", Boolean.valueOf(false));
        playLogMaxStorageSize = GservicesValue.value("finsky.playlog_max_storage_size_bytes", Long.valueOf(2097152));
        playLogRecommendedFileSize = GservicesValue.value("finsky.playlog_recommended_file_size_bytes", Long.valueOf(32768));
        playLogDelayBetweenUploadsMs = GservicesValue.value("finsky.playlog_delay_between_uploads_ms", Long.valueOf(300000));
        playLogMinDelayBetweenUploadsMs = GservicesValue.value("finsky.playlog_min_delay_between_uploads_ms", Long.valueOf(60000));
        playLogServerUrl = GservicesValue.value("finsky.play_log_server_url", "https://android.clients.google.com/play/log");
        playLogImpressionSettleTimeMs = GservicesValue.value("finsky.playlog_impression_settle_time_ms", Long.valueOf(2000));
        vendingRequestTimeoutMs = GservicesValue.value("finsky.vending_request_timeout_ms", Integer.valueOf(20000));
        tabskyMinVersion = GservicesValue.value("finsky.tabsky_min_version", Integer.valueOf(110));
        volleyBufferPoolSizeKb = GservicesValue.value("finsky.volley_buffer_pool_size_kb", Integer.valueOf(256));
        reducedBillingAddressRequiresPhonenumber = GservicesValue.value("finsky.reduced_billing_address_requires_phonenumber", Boolean.valueOf(true));
        enableDcbReducedBillingAddress = GservicesValue.value("finsky.enable_dcb_reduced_billing_address", Boolean.valueOf(true));
        vendingAlwaysSendConfig = GservicesValue.value("vending_always_send_config", Boolean.valueOf(false));
        vendingAddressServerUrl = GservicesValue.value("vending_address_server_url", "http://i18napis.appspot.com/address");
        vendingCarrierProvisioningRefreshFrequencyMs = GservicesValue.value("vending_carrier_ref_freq_ms", Long.valueOf(604800000));
        vendingCarrierProvisioningRetryMs = GservicesValue.value("vending_carrier_prov_retry_ms", Long.valueOf(120000));
        vendingCarrierProvisioningUseTosVersion = GservicesValue.value("vending_carrier_prov_use_tos_version", Boolean.valueOf(false));
        vendingDcbConnectionType = GservicesValue.value("vending_dcb_connection_type", "HIPRI");
        vendingDcbProxyHost = GservicesValue.value("vending_dcb_proxy_host", (String) null);
        vendingDcbProxyPort = GservicesValue.value("vending_dcb_proxy_port", Integer.valueOf(-1));
        vendingDcbPollTimeoutMs = GservicesValue.value("vending_dcb_poll_timeout_ms", Integer.valueOf(5000));
        vendingDcbMmsFallback = GservicesValue.value("vending_dcb_mms_fallback", Boolean.valueOf(true));
        vendingBillingCountriesRefreshMs = GservicesValue.value("vending_billingcountries_refresh_ms", Long.valueOf(432000000));
        vendingCarrierCredentialsBufferMs = GservicesValue.value("vending_carrier_cred_buf_ms", Long.valueOf(300000));
        vendingContentRating = GservicesValue.value("vending_content_rating", Integer.valueOf(4));
        vendingHideContentRating = GservicesValue.value("vending_hide_content_rating", Boolean.valueOf(false));
        dcbDebugOptionsEnabled = GservicesValue.value("finsky.dcb_debug_options_enabled", Boolean.valueOf(false));
        dcb3SetupWhileRoamingEnabled = GservicesValue.value("finsky.dcb3_setup_while_roaming_enabled", Boolean.valueOf(false));
        dcb3VerifyAssociationRetries = GservicesValue.value("finsky.dcb3_verify_association_retries", Integer.valueOf(0));
        dcb3PrepareSendDeviceRebooted = GservicesValue.value("finsky.dcb3_prepare_send_device_rebooted", Boolean.valueOf(false));
        dcb3PassphraseKeyVersion = GservicesValue.value("finsky.dcb3_passphrase_key_version", Integer.valueOf(-1));
        vendingAlarmMaxTimeoutMs = GservicesValue.value("vending_alarm_max_timeout_ms", Long.valueOf(86400000));
        vendingAlarmExpirationTimeoutMs = GservicesValue.value("vending_alarm_expiration_timeout_ms", Long.valueOf(604800000));
        vendingAlarmMinTimeoutMs = GservicesValue.value("vending_alarm_min_timeout_ms", Long.valueOf(10000));
        supportUrl = GservicesValue.value("finsky.support_url", "https://support.google.com/googleplay/digital-content/#topic=3364261");
        helpCenterBackgroundDataUrl = GservicesValue.value("finsky.support_enable_background_data_url", "https://support.google.com/googleplay/answer/1663315");
        editPaymentMethodUrl = GservicesValue.value("finsky.support_edit_payment_method_url", "https://wallet.google.com/manage/paymentMethods");
        instrumentCheckLifetimeMs = GservicesValue.value("finsky.instrument_check_lifetime_ms", Long.valueOf(432000000));
        selectAddinstrumentByDefault = GservicesValue.value("finsky.select_add_instrument_by_default", Boolean.valueOf(false));
        postPurchaseSharingEnabled = GservicesValue.value("finsky.post_purchase_sharing_enabled", Boolean.valueOf(true));
        prePurchaseSharingEnabled = GservicesValue.value("finsky.pre_purchase_sharing_enabled", Boolean.valueOf(true));
        launchUrlsEnabled = GservicesValue.value("finsky.launch_urls_enabled", Boolean.valueOf(true));
        externalReferrerLifespanMs = GservicesValue.value("finsky.external_referrer_lifespan_ms", Long.valueOf(7776000000L));
        subscriptionsEnabled = GservicesValue.value("finsky.subscriptions_enabled", Boolean.valueOf(true));
        enableThirdPartyInlineAppInstalls = GservicesValue.value("finsky.enable_third_party_inline_app_installs", Boolean.valueOf(false));
        logInlineAppInstallReferrerEnabled = GservicesValue.value("finsky.log_inline_app_install_referrer_enabled", Boolean.valueOf(true));
        enableThirdPartyDirectPurchases = GservicesValue.value("finsky.enable_third_party_direct_purchases", Boolean.valueOf(false));
        enableThirdPartyDetailsApi = GservicesValue.value("finsky.enable_third_party_details_api", Boolean.valueOf(false));
        enableDetailsApi = GservicesValue.value("finsky.enable_details_api", Boolean.valueOf(false));
        dailyHygieneRegularIntervalMs = GservicesValue.value("finsky.daily_hygiene_regular_interval_ms", Long.valueOf(86400000));
        dailyHygieneRetryIntervalMs = GservicesValue.value("finsky.daily_hygiene_retry_interval_ms", Long.valueOf(600000));
        dailyHygieneBootDelayMs = GservicesValue.value("finsky.daily_hygiene_boot_delay_ms", Long.valueOf(30000));
        dailyHygieneImmediateDelayMs = GservicesValue.value("finsky.daily_hygiene_immediate_delay_ms", Long.valueOf(1000));
        dailyHygieneJitterFactor = GservicesValue.value("finsky.daily_hygiene_reschedule_jitter_factor", Float.valueOf(0.1f));
        dailyHygieneInitialJitterFactor = GservicesValue.value("finsky.daily_hygiene_initial_reschedule_jitter_factor", Float.valueOf(0.5f));
        dailyHygieneProvisionHoldoffMaxMs = GservicesValue.value("finsky.daily_hygiene_provision_holdoff_max_ms", Long.valueOf(82800000));
        dailyHygieneHoldoffIntervalMs = GservicesValue.value("finsky.daily_hygiene_holdoff_interval_ms", Long.valueOf(60000));
        dailyHygieneHoldoffDuringSelfUpdate = GservicesValue.value("finsky.daily_hygiene_holdoff_during_self_update", Boolean.valueOf(false));
        dailyHygieneImmediateRunVersionCodeLow = GservicesValue.value("finsky.daily_hygiene_emergency_version_code_low", Integer.valueOf(-1));
        dailyHygieneImmediateRunVersionCodeHigh = GservicesValue.value("finsky.daily_hygiene_emergency_version_code_high", Integer.valueOf(-1));
        autoUpdateDeliveryHoldoffMs = GservicesValue.value("finsky.auto_update_delivery_holdoff_ms", Long.valueOf(300000));
        continueUrlExpirationMs = GservicesValue.value("finsky.continue_url_expiration_ms", Long.valueOf(1200000));
        autoUpdateExcludeForegroundServices = GservicesValue.value("finsky.auto_update_exclude_foreground_services", Boolean.valueOf(true));
        autoUpdateExcludeRunningPackagesPre = GservicesValue.value("finsky.auto_update_exclude_running_packages_pre", Boolean.valueOf(true));
        gmsCoreAutoUpdateEnabled = GservicesValue.value("finsky.play_services_auto_update_enabled", Boolean.valueOf(true));
        consistencyTokenEnabled = GservicesValue.value("finsky.consistency_token_enabled", Boolean.valueOf(true));
        eduDevicePolicyApp = GservicesValue.value("finsky.edu_device_policy_package_name", "com.google.android.apps.enterprise.dmagent");
        nlpSharedUserId = GservicesValue.value("finsky.nlp_shared_user_id", "");
        nlpPackageName = GservicesValue.value("finsky.nlp_package_name", "com.google.android.location");
        nlpReinstallSdkVersionMin = GservicesValue.value("finsky.nlp_reinstall_sdk_min", Integer.valueOf(9));
        nlpReinstallSdkVersionMax = GservicesValue.value("finsky.nlp_reinstall_sdk_max", Integer.valueOf(15));
        nlpCleanupConfigurationId = GservicesValue.value("finsky.nlp_cleanup_configuration_id", Integer.valueOf(0));
        nlpCleanupFlagsMask = GservicesValue.value("finsky.nlp_cleanup_flags_mask", Integer.valueOf(129));
        nlpCleanupFlagsSet = GservicesValue.value("finsky.nlp_cleanup_flags_set", Integer.valueOf(129));
        nlpCleanupSdkVersionMin = GservicesValue.value("finsky.nlp_cleanup_sdk_min", Integer.valueOf(16));
        nlpCleanupSdkVersionMax = GservicesValue.value("finsky.nlp_cleanup_sdk_max", Integer.valueOf(16));
        nlpCleanupNlpVersionMin = GservicesValue.value("finsky.nlp_cleanup_nlp_min", Integer.valueOf(1110));
        nlpCleanupNlpVersionMax = GservicesValue.value("finsky.nlp_cleanup_nlp_max", Integer.valueOf(1110));
        nlpCleanupExpectedSignature = GservicesValue.value("finsky.nlp_cleanup_expected_signature", "OJGKRT0HGZNU-LGa8F7GViztV4g");
        nlpCleanupExpectedSignatureTestKeys = GservicesValue.value("finsky.nlp_cleanup_expected_signature_test_keys", "WOHEEz90Qew9LCcCcKFIAtpHug4");
        nlpCleanupUrl = GservicesValue.value("finsky.nlp_cleanup_url", "https://ssl.gstatic.com/android/market_images/apks/nlpfixer/nlpfixer-r01.apk");
        nlpCleanupCookieName = GservicesValue.value("finsky.nlp_cleanup_cookie_name", "");
        nlpCleanupCookieValue = GservicesValue.value("finsky.nlp_cleanup_cookie_value", "");
        nlpCleanupUrlTestKeys = GservicesValue.value("finsky.nlp_cleanup_url_test_keys", "https://ssl.gstatic.com/android/market_images/apks/nlpfixer/nlpfixer-r01-test-keys.apk");
        nlpCleanupCookieNameTestKeys = GservicesValue.value("finsky.nlp_cleanup_cookie_name_test_keys", "");
        nlpCleanupCookieValueTestKeys = GservicesValue.value("finsky.nlp_cleanup_cookie_value_test_keys", "");
        nlpCleanupDowngradeFlag = GservicesValue.value("finsky.nlp_cleanup_downgrade_flag", Boolean.valueOf(false));
        nlpCleanupLogCommonStatuses = GservicesValue.value("finsky.nlp_cleanup_log_common_statuses", Boolean.valueOf(false));
        downloadBytesOverMobileRecommended = GservicesValue.value("finsky.download_bytes_mobile_recommended", Long.valueOf(52428800));
        downloadBytesOverMobileMaximum = GservicesValue.value("finsky.download_bytes_mobile_maximum", Long.valueOf(Long.MAX_VALUE));
        downloadFreeSpaceThresholdBytes = GservicesValue.value("finsky.download_free_space_threshold_bytes", Long.valueOf(-1));
        downloadFreeSpaceApkSizeFactor = GservicesValue.value("finsky.download_free_space_apk_size_factor", Integer.valueOf(100));
        downloadSendBaseVersionCode = GservicesValue.value("finsky.download_send_base_version", Boolean.valueOf(true));
        deliveryDataExpirationMs = GservicesValue.value("finsky.download_deliverydata_expiration", Long.valueOf(14400000));
        downloadPatchFreeSpaceFactor = GservicesValue.value("finsky.download_patch_free_space_factor", Integer.valueOf(210));
        downloadExternalFileSizeMinBytes = GservicesValue.value("finsky.download_external_file_size_min_bytes", Long.valueOf(52428800));
        downloadExternalFreeSpaceFactor = GservicesValue.value("finsky.download_external_free_space_factor", Integer.valueOf(200));
        downloadExternalFreeSpaceThresholdBytes = GservicesValue.value("finsky.download_external_free_space_threshold_bytes", Long.valueOf(67108864));
        preserveForwardLockApiMin = GservicesValue.value("finsky.preserve_forward_lock_api_min", Integer.valueOf(16));
        preserveForwardLockApiMax = GservicesValue.value("finsky.preserve_forward_lock_api_max", Integer.valueOf(19));
        appRestoreHoldoffMs = GservicesValue.value("finsky.app_restore_holdoff_ms", Long.valueOf(120000));
        appRestoreFailsafeMs = GservicesValue.value("finsky.app_restore_failsafe_ms", Long.valueOf(600000));
        appRestoreFetchListMaxAttempts = GservicesValue.value("finsky.app_restore_fetch_list_max_attempts", Integer.valueOf(4));
        appRestoreRetryFetchListHoldoffMs = GservicesValue.value("finsky.app_restore_retry_fetch_list_holdoff_ms", Long.valueOf(120000));
        appRestoreDownloadMaxAttempts = GservicesValue.value("finsky.app_restore_download_max_attempts", Integer.valueOf(4));
        appRestoreRetryDownloadHoldoffMs = GservicesValue.value("finsky.app_restore_retry_download_holdoff_ms", Long.valueOf(240000));
        appRestoreRetryDownloadHoldoffHighPriorityMs = GservicesValue.value("finsky.app_restore_retry_download_holdoff_high_priority_ms", Long.valueOf(30000));
        appRestoreHttpStatusBlacklist = GservicesValue.value("finsky.app_restore_retry_download_blacklist", "198,498");
        appRestoreAppIconMaxAttempts = GservicesValue.value("finsky.app_restore_app_icon_max_attempts", Integer.valueOf(4));
        myLibraryWidgetInteractionClusterMs = GservicesValue.value("finsky.my_library_widget_interactions_cluster_ms", Long.valueOf(1000));
        myLibraryWidgetShorttermDurationMs = GservicesValue.value("finsky.my_library_widget_shortterm_duration_ms", Long.valueOf(86400000));
        myLibraryWidgetMidtermDurationMs = GservicesValue.value("finsky.my_library_widget_midterm_duration_ms", Long.valueOf(604800000));
        myLibraryWidgetImportantContributionFraction = GservicesValue.value("finsky.my_library_widget_important_contribution_fraction", Float.valueOf(0.2f));
        myLibraryWidgetShorttermDecay = GservicesValue.value("finsky.my_library_widget_shortterm_decay", Float.valueOf(0.8f));
        myLibraryWidgetHasContentScoreMap = GservicesValue.value("finsky.my_library_has_content_scores", "0:15");
        myLibraryWidgetShorttermScores = GservicesValue.value("finsky.my_library_widget_shortterm_scores", "0:5");
        myLibraryWidgeMidtermScores = GservicesValue.value("finsky.my_library_widget_midterm_scores", "0:1");
        myLibraryWidgetAlwaysIncludeMostRecentBackend = GservicesValue.value("finsky.my_library_widget_always_include_most_recent", Boolean.valueOf(true));
        recommendationsWidgetFlipIntervalMs = GservicesValue.value("finsky.recs_widget_flip_interval_ms", Integer.valueOf(-1));
        consumptionAppTimeoutMs = GservicesValue.value("finsky.consumption_app_timeout_ms", Long.valueOf(7000));
        consumptionAppImageTimeoutMs = GservicesValue.value("finsky.consumption_app_image_timeout_ms", Long.valueOf(5000));
        recommendationsFetchTimeoutMs = GservicesValue.value("finsky.recommendations_fetch_timeout_ms", Long.valueOf(15000));
        minimumVideosVersionCodePreHoneycomb = GservicesValue.value("finsky.minimum_videos_app_version_code_pre_honeycomb", Integer.valueOf(2009));
        minimumVideosVersionCodeHoneycombPlus = GservicesValue.value("finsky.minimum_videos_app_version_code_post_honeycomb", Integer.valueOf(20090));
        minimumMusicVersionCode = GservicesValue.value("finsky.minimum_music_app_version_code", Integer.valueOf(1409));
        minimumNumberOfRecs = GservicesValue.value("finsky.minimum_number_of_recommendations", Integer.valueOf(4));
        recommendationTtlMs = GservicesValue.value("finsky.recommendation_ttl_ms", Long.valueOf(172800000));
        gaiaAuthValidityMs = GservicesValue.value("finsky.gaia_auth_validity_ms", Long.valueOf(0));
        platformAntiMalwareEnabled = GservicesValue.value("finsky.platform_anti_malware_enabled", Boolean.valueOf(true));
        platformAntiMalwareDialogDelayMs = GservicesValue.value("finsky.platform_anti_malware_dialog_delay_ms", Long.valueOf(3600000));
        antiMalwareActivityEnabled = GservicesValue.value("finsky.anti_malware_activity_enabled", Boolean.valueOf(true));
        verifyInstalledPackagesMinimumWaitMs = GservicesValue.value("finsky.verify_installed_packages_minimum_wait_time_ms", Long.valueOf(518400000));
        verifyInstalledPackagesTimeoutMs = GservicesValue.value("finsky.verify_installed_packages_timeout_ms", Integer.valueOf(15000));
        verifyInstalledPackagesNumRetries = GservicesValue.value("finsky.verify_installed_packages_retries", Integer.valueOf(8));
        verifyInstalledPackagesBackoffMultiplier = GservicesValue.value("finsky.verify_installed_packages_backoff_multiplier", Float.valueOf(2.0f));
        verifyInstalledPackagesEnabled = GservicesValue.value("finsky.verify_installed_packages_enabled", Boolean.valueOf(true));
        verifyInstalledPlayPackagesEnabled = GservicesValue.value("finsky.verify_installed_play_packages_enabled", Boolean.valueOf(true));
        enableReviewComments = GservicesValue.value("finsky.enable_review_comments", Boolean.valueOf(true));
        enableRemoveAppsFromLibrary = GservicesValue.value("finsky.enable_remove_apps_from_library", Boolean.valueOf(true));
        iabV3SubscriptionsEnabled = GservicesValue.value("finsky.iabv3_subscriptions_enabled", Boolean.valueOf(true));
        iabV3MaxPurchasesInResponse = GservicesValue.value("finsky.iabv3_max_purchases_in_response", Integer.valueOf(100));
        iabV3NetworkTimeoutMs = GservicesValue.value("finsky.iabv3_network_timeout_ms", Long.valueOf(20000));
        iabV3SkuDetailsMaxSize = GservicesValue.value("finsky.iabv3_sku_details_max_size", Integer.valueOf(20));
        iabV3FirstPartyApiEnabled = GservicesValue.value("finsky.iabv3_first_party_api_enabled", Boolean.valueOf(true));
        iabV3FirstPartyApiUnrestrictedAccess = GservicesValue.value("finsky.iabv3_first_party_api_unrestricted_access", Boolean.valueOf(false));
        placesApiBiasRadiusMeters = GservicesValue.value("finsky.places_api_bias_radius_meters", Integer.valueOf(50000));
        whitelistedPlacesApiCountries = GservicesValue.value("finsky.whitelisted_places_api_countries", "0:CA,CH,US");
        placesApiKey = GservicesValue.value("finsky.places_api_key", "AIzaSyCsc46SHdb57jPJa9fo7euV_HBDgwdrXsE");
        enablePeopleSuggestWidget = GservicesValue.value("finsky.enable_people_suggest_widget", Boolean.valueOf(true));
        lightPurchaseAutoDismissMs = GservicesValue.value("finsky.light_purchase_auto_dismiss_ms", Long.valueOf(2500));
        lightPurchaseOptimisticProvisioning = GservicesValue.value("finsky.light_purchase_optimistic_provisioning", Boolean.valueOf(true));
        defaultPurchaseAuthentication = GservicesValue.value("finsky.default_purchase_authentication", Integer.valueOf(1));
        passwordRecoveryUrl = GservicesValue.value("finsky.password_recovery_url", "https://accounts.google.com/RecoverAccount?fpOnly=1&Email=%email%");
        resetPinUrl = GservicesValue.value("finsky.reset_pin_url", "https://accounts.google.com/ResetPin?Email=%email%");
        passwordMaxFailedAttempts = GservicesValue.value("finsky.password_max_failed_attempts", Integer.valueOf(5));
        maxAutoUpdateDialogShownCount = GservicesValue.value("finsky.max_times_auto_update_cleanup_shown", Integer.valueOf(3));
        autoUpdateDialogFirstBackoffDays = GservicesValue.value("finsky.auto_update_cleanup_first_backoff_days", Integer.valueOf(7));
        autoUpdateDialogSecondBackoffDays = GservicesValue.value("finsky.auto_update_cleanup_second_backoff_days", Integer.valueOf(23));
        autoUpdateDialogSubsequentBackoffDays = GservicesValue.value("finsky.auto_update_cleanup_subsequent_backoff_days", Integer.valueOf(-1));
        skipAutoUpdateCleanupClientVersionCheck = GservicesValue.value("finsky.skip_auto_update_cleanup_client_version_check", Boolean.valueOf(false));
        playGamesInstallSuggestionMaxShownCount = GservicesValue.value("finsky.play_games_install_suggestion_max_times_shown", Integer.valueOf(0));
        playGamesGmsCoreMinVersion = GservicesValue.value("finsky.play_games_gms_core_min_version", Integer.valueOf(3150000));
        playGamesInstallSuggestionOnlyWhenGameFeatures = GservicesValue.value("finsky.play_games_install_suggestion_only_when_game_features", Boolean.valueOf(false));
        playGamesInstallSuggestionFirstBackoffMs = GservicesValue.value("finsky.play_games_install_suggestion_first_backoff_ms", Long.valueOf(604800000));
        playGamesInstallSuggestionSubsequentBackoffMs = GservicesValue.value("finsky.play_games_install_suggestion_subsequent_backoff_ms", Long.valueOf(2592000000L));
        playGamesDocId = GservicesValue.value("finsky.play_games_doc_id", "com.google.android.play.games");
        enableSessionStatsLog = GservicesValue.value("finsky.enable_session_stats_log", Boolean.valueOf(true));
        dcb2SetupDelayTosLoading = GservicesValue.value("finsky.dcb2_setup_delay_tos_loading", Long.valueOf(3000));
        musicAppSubscriptionBackendDocidBlacklist = GservicesValue.value("finsky.music_app_subscription_backend_docid_blacklist", "Saeaaaaaa");
        musicAllAccessSubscriptionBackendDocid = GservicesValue.value("finsky.all_access_backend_docid", "Saeaaaaaa");
        musicAppSubscriptionResignupEnabled = GservicesValue.value("finsky.music_app_subscription_resignup_enabled", Boolean.valueOf(false));
        additionalExperiments = GservicesValue.value("finsky.additional_experiments", (String) null);
        recentlyUpdatedWindowSizeMs = GservicesValue.value("finsky.recently_updated_window_size_ms", Long.valueOf(259200000));
        outstandingNotificationTimeDelayMs = GservicesValue.value("finsky.outstanding_notification_time_delay_ms", Long.valueOf(259200000));
        corpusAwarenessThresholdBooks = GservicesValue.value("finsky.corpusAwarenessThreshold.books", Integer.valueOf(6));
        corpusAwarenessThresholdMagazines = GservicesValue.value("finsky.corpusAwarenessThreshold.magazines", Integer.valueOf(6));
        corpusAwarenessThresholdMovies = GservicesValue.value("finsky.corpusAwarenessThreshold.movies", Integer.valueOf(1));
        corpusAwarenessThresholdMusic = GservicesValue.value("finsky.corpusAwarenessThreshold.music", Integer.valueOf(6));
        autoUpdateJobSchedulerGearheadDelayMs = GservicesValue.value("finsky.auto_update_job_scheduler_gearhead_delay", Long.valueOf(3600000));
        autoUpdateJobSchedulerGearheadTimeoutMs = GservicesValue.value("finsky.auto_update_job_scheduler_gearhead_delay", Long.valueOf(604800000));
        autoUpdateWifiCheckIntervalMs = GservicesValue.value("finsky.auto_update_wifi_check_interval", Long.valueOf(3600000));
        autoUpdateJobSchedulerTimeoutMs = GservicesValue.value("finsky.auto_update_job_scheduler_timeout_ms", Long.valueOf(86400000));
        videoAppTrailerPlaybackMinVersion = GservicesValue.value("finsky.video_app_trailer_playback_min_version", Integer.valueOf(27030));
        firstNewsstandAppVersion = GservicesValue.value("finsky.newsstand_app_first_version", Integer.valueOf(132340703));
        gelPackageName = GservicesValue.value("finsky.gel_package_name", "com.google.android.googlequicksearchbox");
        libraryReplicatorRescheduleDelayMs = GservicesValue.value("finsky.library_replicator_reschedule_delay_ms", Integer.valueOf(1000));
        positiveRateThreshold = GservicesValue.value("finsky.positive_rate_threshold", Integer.valueOf(3));
        peoplePageWarmWelcomeGraphicUrl = GservicesValue.value("finsky.peoplePageWarmWelcomeGraphicUrl", "https://lh6.ggpht.com/MBGKEdyM2S9-d0wZxNGZkdrTDHeT6iU3fANSMYh6R8cw6GNlRoEi_pMzxoZhJTLl4A");
        peoplePageWarmWelcomeButtonIconUrl = GservicesValue.value("finsky.peoplePageWarmWelcomeButtonIconUrl", "https://lh3.ggpht.com/UFLxPwW24-zpdw50aPXy07XUncvFN7BT4LW0yIKB6uNWWljHiiWalKAddBUHl15cgmg");
        setupWizardRestoreHeaderGraphicUrl = GservicesValue.value("finsky.setupWizardRestoreHeaderGraphicUrl", "https://lh3.ggpht.com/mVyozFkAy-ppNcs7MK9cGlbvH6Gzahl0x_XiOLIk-rUMd9TPtZUCVtivtA53EqcMcQ");
        setupWizardRestoreWideHeaderGraphicUrl = GservicesValue.value("finsky.setupWizardRestoreWideHeaderGraphicUrl", "https://lh6.ggpht.com/MJOZe02zps-3ks_-mD8e0H9XInCVD5Un-4aYvP1gOSUhouHrC4wvqwopxg0NsxUUpoY");
        setupWizardRestoreFinalHoldHeaderUrl = GservicesValue.value("finsky.setupWizardRestoreFinalHoldHeaderUrl", "https://lh6.ggpht.com/-jHSfNHsSAhHV2mHP1moDA8BZHNEQFTTeLulxy327nlGm5eYE_c5hL9iwBgmMgS1b1k");
        setupWizardRestoreFinalHoldHeaderLandscapeUrl = GservicesValue.value("finsky.setupWizardRestoreFinalHoldHeaderLandscapeUrl", "https://lh6.ggpht.com/TWBB8vzWLPJm4iYShK_-7jcoPoE5ea9E8kICksvYhim1XEB1Njc8m5JK1uc8Bephpg");
        setupWizardRestoreFinalHoldHeaderTabletUrl = GservicesValue.value("finsky.setupWizardRestoreFinalHoldHeaderTabletUrl", "https://lh5.ggpht.com/oc1mRJCrLUcAdXhuVYW2ke0v78bTYzp5W6eSFoU8zCaldflOgmRpaMTBEqTDIJwazHc");
        setupWizardRestoreFinalHoldShortMs = GservicesValue.value("finsky.setup_wizard_restore_final_hold_short_ms", Long.valueOf(60000));
        setupWizardRestoreFinalHoldLongMs = GservicesValue.value("finsky.setup_wizard_restore_final_hold_long_ms", Long.valueOf(180000));
        setupWizardPaymentHeaderGraphicUrl = GservicesValue.value("finsky.setupWizardPaymentHeaderGraphicUrl", "https://lh3.ggpht.com/Abae-7-cb7aY274FnRM2l-PL9VVBIm_Gl0mESZf6JJQNjhe50ICjGUorkNLRiE4Q5Q");
        setupWizardPaymentHeaderWideGraphicUrl = GservicesValue.value("finsky.setupWizardPaymentHeaderWideGraphicUrl", "https://lh4.ggpht.com/7Qt-tnJI4-P5n7PCvoyzL7oBu5NsbpbOVbO4H-evP3k_Pzom57o47T23QKhiLsRB1A");
        setupWizardForceResizeForKeyboardInFullscreen = GservicesValue.value("finsky.setupWizardForceResizeForKeyboardInFullscreen", Boolean.valueOf(true));
        clientMutationCacheCirclesModelCacheSize = GservicesValue.value("finsky.client_mutation_cache_circles_model_cache_size", Integer.valueOf(100));
        myLibraryWidgetBackgroundImageLocation = GservicesValue.value("finsky.myLibraryWidget.backgroundImageLocation", "/system/media/play_widget_background.png");
        musicAllAccessSignUpIntentUrl = GservicesValue.value("finsky.music_all_access_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=album_detail_page&utm_campaign=30daytrial");
        setupWizardEarlyUpdateEnable = GservicesValue.value("finsky.setup_wizard_early_update_enable", Boolean.valueOf(true));
        setupWizardEarlyUpdateDeadlockMaxMs = GservicesValue.value("finsky.setup_wizard_early_update_deadlock_max_ms", Long.valueOf(5000));
        unsubmittedReviewLifespanMs = GservicesValue.value("finsky.unsubmitted_reviews_max_lifespan_ms", Long.valueOf(2592000000L));
        supportedAccountTypes = GservicesValue.value("finsky.supported_account_types", "com.google.work");
        surveySiteIdOverallApp = GservicesValue.value("finsky.hats.survey_site_id_overall_app", "gxadhtcppqz4aewwxotbhbc5lm");
        surveySiteIdSearchResults = GservicesValue.value("finsky.hats.survey_site_id_search_results", "tiyln7mdroeylhev4m736lnsmy");
        surveySiteIdSearchResultsControlGroup = GservicesValue.value("finsky.hats.survey_site_id_search_results_control_group", "tvdzhhl47xlshtqukvrtdmfcim");
    }
}
