package com.android.vending;

public final class R {

    public static final class styleable {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 24;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 26;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 25;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] AdsAttrs;
        public static final int AdsAttrs_adSize = 0;
        public static final int AdsAttrs_adSizes = 1;
        public static final int AdsAttrs_adUnitId = 2;
        public static final int[] AppDataSearch;
        public static final int[] BindingFrameLayout;
        public static final int BindingFrameLayout_bind__isOwnedByParent = 0;
        public static final int BindingFrameLayout_bind__supportsAnimationCapture = 1;
        public static final int[] BindingLinearLayout;
        public static final int BindingLinearLayout_bind__isOwnedByParent = 0;
        public static final int BindingLinearLayout_bind__supportsAnimationCapture = 1;
        public static final int[] BindingRelativeLayout;
        public static final int BindingRelativeLayout_bind__isOwnedByParent = 0;
        public static final int BindingRelativeLayout_bind__supportsAnimationCapture = 1;
        public static final int[] BoundImageView;
        public static final int BoundImageView_bindDrawable = 1;
        public static final int BoundImageView_bindImageUri = 0;
        public static final int[] BoundTextView;
        public static final int BoundTextView_bindDrawableEnd = 4;
        public static final int BoundTextView_bindDrawableStart = 3;
        public static final int BoundTextView_bindText = 1;
        public static final int BoundTextView_bindTextColor = 2;
        public static final int BoundTextView_bind__editModeText = 0;
        public static final int[] BoundView;
        public static final int BoundView_bindBackground = 0;
        public static final int BoundView_bindContentDescription = 1;
        public static final int BoundView_bindEnabled = 2;
        public static final int BoundView_bindInvisibility = 3;
        public static final int BoundView_bindMinHeight = 4;
        public static final int BoundView_bindOnClickListener = 5;
        public static final int BoundView_bindPaddingTop = 6;
        public static final int BoundView_bindTransitionName = 7;
        public static final int BoundView_bindVisibility = 8;
        public static final int[] BucketRow;
        public static final int BucketRow_same_child_height = 0;
        public static final int BucketRow_same_child_width = 1;
        public static final int[] CheckableLinearLayout;
        public static final int CheckableLinearLayout_checkableChildId = 0;
        public static final int[] CompatTextView;
        public static final int CompatTextView_textAllCaps = 0;
        public static final int[] ContentFrame;
        public static final int ContentFrame_content = 0;
        public static final int ContentFrame_contentId = 1;
        public static final int[] Corpus;
        public static final int Corpus_contentProviderUri = 2;
        public static final int Corpus_corpusId = 0;
        public static final int Corpus_corpusVersion = 1;
        public static final int Corpus_schemaOrgType = 4;
        public static final int Corpus_trimmable = 3;
        public static final int[] DetailsColumnLayout;
        public static final int DetailsColumnLayout_has_leading_gap = 0;
        public static final int DetailsColumnLayout_leading_hero_section_id = 1;
        public static final int[] DetailsSectionStack;
        public static final int DetailsSectionStack_separator_inset = 0;
        public static final int DetailsSectionStack_show_trailing_separator = 1;
        public static final int[] DetailsTextBlock;
        public static final int DetailsTextBlock_corpus_style_xmargin = 1;
        public static final int DetailsTextBlock_regular_style_xmargin = 0;
        public static final int[] DownloadStatusView;
        public static final int DownloadStatusView_playDownloadArcColorDownload = 5;
        public static final int DownloadStatusView_playDownloadArcColorOffline = 3;
        public static final int DownloadStatusView_playDownloadArcColorOnline = 2;
        public static final int DownloadStatusView_playDownloadArcColorPress = 4;
        public static final int DownloadStatusView_playDownloadArcInset = 0;
        public static final int DownloadStatusView_playDownloadArcMinPercent = 6;
        public static final int DownloadStatusView_playDownloadArcWidth = 1;
        public static final int DownloadStatusView_playDownloadDownloadDrawable = 8;
        public static final int DownloadStatusView_playDownloadFinishDrawable = 9;
        public static final int DownloadStatusView_playDownloadPressDrawable = 7;
        public static final int[] DrawerArrowToggle;
        public static final int DrawerArrowToggle_barSize = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_middleBarArrowSize = 5;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int DrawerArrowToggle_topBottomBarArrowSize = 4;
        public static final int[] FeatureParam;
        public static final int FeatureParam_paramName = 0;
        public static final int FeatureParam_paramValue = 1;
        public static final int[] FifeImageView;
        public static final int FifeImageView_fade_in_after_load = 4;
        public static final int FifeImageView_fixed_bounds = 0;
        public static final int FifeImageView_is_avatar = 1;
        public static final int FifeImageView_is_avatar_no_ring = 2;
        public static final int FifeImageView_request_scale_factor = 5;
        public static final int FifeImageView_zoom = 3;
        public static final int[] FlowLayoutManager_Layout;
        public static final int[] FlowLayoutManager_Layout_Style;
        public static final int FlowLayoutManager_Layout_Style_layout_flmStyle = 0;
        public static final int FlowLayoutManager_Layout_layout_flmFlow = 15;
        public static final int FlowLayoutManager_Layout_layout_flmFlowHeight = 21;
        public static final int FlowLayoutManager_Layout_layout_flmFlowInsetBottom = 19;
        public static final int FlowLayoutManager_Layout_layout_flmFlowInsetEnd = 18;
        public static final int FlowLayoutManager_Layout_layout_flmFlowInsetStart = 17;
        public static final int FlowLayoutManager_Layout_layout_flmFlowInsetTop = 16;
        public static final int FlowLayoutManager_Layout_layout_flmFlowWidth = 20;
        public static final int FlowLayoutManager_Layout_layout_flmGridColumnCount = 5;
        public static final int FlowLayoutManager_Layout_layout_flmGridInsetEnd = 3;
        public static final int FlowLayoutManager_Layout_layout_flmGridInsetStart = 2;
        public static final int FlowLayoutManager_Layout_layout_flmGridMinCellSize = 6;
        public static final int FlowLayoutManager_Layout_layout_flmHeight = 1;
        public static final int FlowLayoutManager_Layout_layout_flmLineWrap = 22;
        public static final int FlowLayoutManager_Layout_layout_flmMargin = 7;
        public static final int FlowLayoutManager_Layout_layout_flmMarginBottom = 11;
        public static final int FlowLayoutManager_Layout_layout_flmMarginBottomForLastLine = 13;
        public static final int FlowLayoutManager_Layout_layout_flmMarginEnd = 10;
        public static final int FlowLayoutManager_Layout_layout_flmMarginStart = 9;
        public static final int FlowLayoutManager_Layout_layout_flmMarginTop = 8;
        public static final int FlowLayoutManager_Layout_layout_flmMarginTopForFirstLine = 12;
        public static final int FlowLayoutManager_Layout_layout_flmMaxGridWidth = 4;
        public static final int FlowLayoutManager_Layout_layout_flmVAlign = 14;
        public static final int FlowLayoutManager_Layout_layout_flmWidth = 0;
        public static final int[] GlobalSearch;
        public static final int[] GlobalSearchCorpus;
        public static final int GlobalSearchCorpus_allowShortcuts = 0;
        public static final int[] GlobalSearchSection;
        public static final int GlobalSearchSection_sectionContent = 1;
        public static final int GlobalSearchSection_sectionType = 0;
        public static final int GlobalSearch_defaultIntentAction = 3;
        public static final int GlobalSearch_defaultIntentActivity = 5;
        public static final int GlobalSearch_defaultIntentData = 4;
        public static final int GlobalSearch_searchEnabled = 0;
        public static final int GlobalSearch_searchLabel = 1;
        public static final int GlobalSearch_settingsDescription = 2;
        public static final int[] HeroGraphicView;
        public static final int HeroGraphicView_full_screen_on = 0;
        public static final int[] HistogramTable;
        public static final int HistogramTable_bar_height = 1;
        public static final int HistogramTable_bar_margin = 3;
        public static final int HistogramTable_labels_on = 0;
        public static final int HistogramTable_max_bar_width = 2;
        public static final int[] HistogramView;
        public static final int HistogramView_needs_height_correction = 0;
        public static final int HistogramView_shows_bottom_separator = 1;
        public static final int[] IMECorpus;
        public static final int IMECorpus_inputEnabled = 0;
        public static final int IMECorpus_sourceClass = 1;
        public static final int IMECorpus_toAddressesSection = 5;
        public static final int IMECorpus_userInputSection = 3;
        public static final int IMECorpus_userInputTag = 2;
        public static final int IMECorpus_userInputValue = 4;
        public static final int[] LinearLayoutCompat;
        public static final int[] LinearLayoutCompat_Layout;
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int[] ListPopupWindow;
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int[] LoadingImageView;
        public static final int LoadingImageView_circleCrop = 2;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 0;
        public static final int[] MapAttrs;
        public static final int MapAttrs_cameraBearing = 1;
        public static final int MapAttrs_cameraTargetLat = 2;
        public static final int MapAttrs_cameraTargetLng = 3;
        public static final int MapAttrs_cameraTilt = 4;
        public static final int MapAttrs_cameraZoom = 5;
        public static final int MapAttrs_liteMode = 6;
        public static final int MapAttrs_mapType = 0;
        public static final int MapAttrs_uiCompass = 7;
        public static final int MapAttrs_uiMapToolbar = 15;
        public static final int MapAttrs_uiRotateGestures = 8;
        public static final int MapAttrs_uiScrollGestures = 9;
        public static final int MapAttrs_uiTiltGestures = 10;
        public static final int MapAttrs_uiZoomControls = 11;
        public static final int MapAttrs_uiZoomGestures = 12;
        public static final int MapAttrs_useViewLifecycle = 13;
        public static final int MapAttrs_zOrderOnTop = 14;
        public static final int[] MaxSizeLayoutHeight;
        public static final int MaxSizeLayoutHeight_max_size_layout_height = 0;
        public static final int[] MaxWidthView;
        public static final int MaxWidthView_max_width = 0;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int[] PlayActionButton;
        public static final int PlayActionButton_action_bottom_padding = 5;
        public static final int PlayActionButton_action_style = 0;
        public static final int PlayActionButton_action_top_padding = 4;
        public static final int PlayActionButton_action_xpadding = 3;
        public static final int PlayActionButton_draw_as_label = 1;
        public static final int PlayActionButton_local_priority = 6;
        public static final int PlayActionButton_use_all_caps_in_label_mode = 2;
        public static final int[] PlayAvatarPack;
        public static final int PlayAvatarPack_primary_avatar_size = 0;
        public static final int[] PlayCardBaseView;
        public static final int PlayCardBaseView_card_avatar_snippet_margin_left = 3;
        public static final int PlayCardBaseView_card_owned_status_rendering_type = 4;
        public static final int PlayCardBaseView_card_show_inline_creator_badge = 0;
        public static final int PlayCardBaseView_card_supports_subtitle_and_rating = 1;
        public static final int PlayCardBaseView_card_text_only_snippet_margin_left = 2;
        public static final int[] PlayCardClusterViewContent;
        public static final int PlayCardClusterViewContent_card_content_padding_bottom = 1;
        public static final int PlayCardClusterViewContent_card_content_padding_top = 0;
        public static final int[] PlayCardClusterViewHeader;
        public static final int PlayCardClusterViewHeader_header_xpadding = 1;
        public static final int PlayCardClusterViewHeader_min_header_height = 0;
        public static final int[] PlayCardThumbnail;
        public static final int PlayCardThumbnail_app_thumbnail_padding = 1;
        public static final int PlayCardThumbnail_person_thumbnail_padding = 2;
        public static final int PlayCardThumbnail_thumbnail_id = 0;
        public static final int[] PlayCardViewFeatured;
        public static final int PlayCardViewFeatured_featured_card_layout_type = 0;
        public static final int[] PlayCardViewGroup;
        public static final int PlayCardViewGroup_playCardBackgroundColor = 0;
        public static final int PlayCardViewGroup_playCardClipToOutline = 4;
        public static final int PlayCardViewGroup_playCardCornerRadius = 1;
        public static final int PlayCardViewGroup_playCardElevation = 2;
        public static final int PlayCardViewGroup_playCardInset = 3;
        public static final int[] PlayCirclesButton;
        public static final int PlayCirclesButton_is_flat = 0;
        public static final int[] PlayEduCardButtonPanel;
        public static final int PlayEduCardButtonPanel_playSpacing = 0;
        public static final int[] PlayImageView;
        public static final int PlayImageView_fixed_bounds = 0;
        public static final int PlayImageView_is_avatar = 1;
        public static final int PlayImageView_zoom = 2;
        public static final int[] PlaySeparatorLayout;
        public static final int PlaySeparatorLayout_separator_padding_bottom = 1;
        public static final int PlaySeparatorLayout_separator_padding_left = 2;
        public static final int PlaySeparatorLayout_separator_padding_right = 3;
        public static final int PlaySeparatorLayout_separator_padding_top = 0;
        public static final int[] PlayTextView;
        public static final int PlayTextView_allowsCompactLineSpacing = 0;
        public static final int PlayTextView_decoration_position = 5;
        public static final int PlayTextView_lastLineOverdrawAllCaps = 4;
        public static final int PlayTextView_lastLineOverdrawColor = 1;
        public static final int PlayTextView_lastLineOverdrawHint = 2;
        public static final int PlayTextView_lastLineOverdrawHintColor = 3;
        public static final int[] PopupWindow;
        public static final int[] PopupWindowBackgroundState;
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 1;
        public static final int[] ProportionalOuterFrame;
        public static final int ProportionalOuterFrame_proportion = 0;
        public static final int[] SearchView;
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 7;
        public static final int SearchView_commitIcon = 11;
        public static final int SearchView_goIcon = 8;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 13;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchIcon = 9;
        public static final int SearchView_submitBackground = 14;
        public static final int SearchView_suggestionRowLayout = 12;
        public static final int SearchView_voiceIcon = 10;
        public static final int[] Section;
        public static final int[] SectionFeature;
        public static final int SectionFeature_featureType = 0;
        public static final int Section_indexPrefixes = 4;
        public static final int Section_noIndex = 2;
        public static final int Section_schemaOrgProperty = 6;
        public static final int Section_sectionFormat = 1;
        public static final int Section_sectionId = 0;
        public static final int Section_sectionWeight = 3;
        public static final int Section_subsectionSeparator = 5;
        public static final int[] SeparatorLinearLayout;
        public static final int SeparatorLinearLayout_separator_position = 0;
        public static final int[] SetupWizardIllustration;
        public static final int SetupWizardIllustration_aspectRatio = 1;
        public static final int SetupWizardIllustration_collapsable = 0;
        public static final int[] SingleLineContainer;
        public static final int SingleLineContainer_flexibleChildId = 0;
        public static final int[] Spinner;
        public static final int Spinner_android_background = 1;
        public static final int Spinner_android_dropDownHorizontalOffset = 5;
        public static final int Spinner_android_dropDownSelector = 2;
        public static final int Spinner_android_dropDownVerticalOffset = 6;
        public static final int Spinner_android_dropDownWidth = 4;
        public static final int Spinner_android_gravity = 0;
        public static final int Spinner_android_popupBackground = 3;
        public static final int Spinner_disableChildrenWhenDisabled = 10;
        public static final int Spinner_popupPromptView = 9;
        public static final int Spinner_prompt = 7;
        public static final int Spinner_spinnerMode = 8;
        public static final int[] StarRatingBar;
        public static final int StarRatingBar_gap = 5;
        public static final int StarRatingBar_range = 1;
        public static final int StarRatingBar_rating = 0;
        public static final int StarRatingBar_star_bg_color = 4;
        public static final int StarRatingBar_star_color = 3;
        public static final int StarRatingBar_star_height = 2;
        public static final int[] SwitchCompat;
        public static final int[] SwitchCompatTextAppearance;
        public static final int SwitchCompatTextAppearance_android_textColor = 1;
        public static final int SwitchCompatTextAppearance_android_textSize = 0;
        public static final int SwitchCompatTextAppearance_textAllCaps = 2;
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 9;
        public static final int SwitchCompat_splitTrack = 8;
        public static final int SwitchCompat_switchMinWidth = 6;
        public static final int SwitchCompat_switchPadding = 7;
        public static final int SwitchCompat_switchTextAppearance = 5;
        public static final int SwitchCompat_thumbTextPadding = 4;
        public static final int SwitchCompat_track = 3;
        public static final int[] Theme;
        public static final int Theme_actionBarDivider = 20;
        public static final int Theme_actionBarItemBackground = 21;
        public static final int Theme_actionBarPopupTheme = 14;
        public static final int Theme_actionBarSize = 19;
        public static final int Theme_actionBarSplitStyle = 16;
        public static final int Theme_actionBarStyle = 15;
        public static final int Theme_actionBarTabBarStyle = 10;
        public static final int Theme_actionBarTabStyle = 9;
        public static final int Theme_actionBarTabTextStyle = 11;
        public static final int Theme_actionBarTheme = 17;
        public static final int Theme_actionBarWidgetTheme = 18;
        public static final int Theme_actionButtonStyle = 44;
        public static final int Theme_actionDropDownStyle = 39;
        public static final int Theme_actionMenuTextAppearance = 22;
        public static final int Theme_actionMenuTextColor = 23;
        public static final int Theme_actionModeBackground = 26;
        public static final int Theme_actionModeCloseButtonStyle = 25;
        public static final int Theme_actionModeCloseDrawable = 28;
        public static final int Theme_actionModeCopyDrawable = 30;
        public static final int Theme_actionModeCutDrawable = 29;
        public static final int Theme_actionModeFindDrawable = 34;
        public static final int Theme_actionModePasteDrawable = 31;
        public static final int Theme_actionModePopupWindowStyle = 36;
        public static final int Theme_actionModeSelectAllDrawable = 32;
        public static final int Theme_actionModeShareDrawable = 33;
        public static final int Theme_actionModeSplitBackground = 27;
        public static final int Theme_actionModeStyle = 24;
        public static final int Theme_actionModeWebSearchDrawable = 35;
        public static final int Theme_actionOverflowButtonStyle = 12;
        public static final int Theme_actionOverflowMenuStyle = 13;
        public static final int Theme_activityChooserViewStyle = 51;
        public static final int Theme_android_windowAnimationStyle = 1;
        public static final int Theme_android_windowIsFloating = 0;
        public static final int Theme_buttonBarButtonStyle = 46;
        public static final int Theme_buttonBarStyle = 45;
        public static final int Theme_colorAccent = 78;
        public static final int Theme_colorButtonNormal = 82;
        public static final int Theme_colorControlActivated = 80;
        public static final int Theme_colorControlHighlight = 81;
        public static final int Theme_colorControlNormal = 79;
        public static final int Theme_colorPrimary = 76;
        public static final int Theme_colorPrimaryDark = 77;
        public static final int Theme_colorSwitchThumbNormal = 83;
        public static final int Theme_dividerHorizontal = 50;
        public static final int Theme_dividerVertical = 49;
        public static final int Theme_dropDownListViewStyle = 68;
        public static final int Theme_dropdownListPreferredItemHeight = 40;
        public static final int Theme_editTextBackground = 57;
        public static final int Theme_editTextColor = 56;
        public static final int Theme_homeAsUpIndicator = 43;
        public static final int Theme_listChoiceBackgroundIndicator = 75;
        public static final int Theme_listPopupWindowStyle = 69;
        public static final int Theme_listPreferredItemHeight = 63;
        public static final int Theme_listPreferredItemHeightLarge = 65;
        public static final int Theme_listPreferredItemHeightSmall = 64;
        public static final int Theme_listPreferredItemPaddingLeft = 66;
        public static final int Theme_listPreferredItemPaddingRight = 67;
        public static final int Theme_panelBackground = 72;
        public static final int Theme_panelMenuListTheme = 74;
        public static final int Theme_panelMenuListWidth = 73;
        public static final int Theme_popupMenuStyle = 54;
        public static final int Theme_popupWindowStyle = 55;
        public static final int Theme_searchViewStyle = 62;
        public static final int Theme_selectableItemBackground = 47;
        public static final int Theme_selectableItemBackgroundBorderless = 48;
        public static final int Theme_spinnerDropDownItemStyle = 42;
        public static final int Theme_spinnerStyle = 41;
        public static final int Theme_switchStyle = 58;
        public static final int Theme_textAppearanceLargePopupMenu = 37;
        public static final int Theme_textAppearanceListItem = 70;
        public static final int Theme_textAppearanceListItemSmall = 71;
        public static final int Theme_textAppearanceSearchResultSubtitle = 60;
        public static final int Theme_textAppearanceSearchResultTitle = 59;
        public static final int Theme_textAppearanceSmallPopupMenu = 38;
        public static final int Theme_textColorSearchUrl = 61;
        public static final int Theme_toolbarNavigationButtonStyle = 53;
        public static final int Theme_toolbarStyle = 52;
        public static final int Theme_windowActionBar = 2;
        public static final int Theme_windowActionBarOverlay = 3;
        public static final int Theme_windowActionModeOverlay = 4;
        public static final int Theme_windowFixedHeightMajor = 8;
        public static final int Theme_windowFixedHeightMinor = 6;
        public static final int Theme_windowFixedWidthMajor = 5;
        public static final int Theme_windowFixedWidthMinor = 7;
        public static final int[] Toolbar;
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_collapseContentDescription = 19;
        public static final int Toolbar_collapseIcon = 18;
        public static final int Toolbar_contentInsetEnd = 5;
        public static final int Toolbar_contentInsetLeft = 6;
        public static final int Toolbar_contentInsetRight = 7;
        public static final int Toolbar_contentInsetStart = 4;
        public static final int Toolbar_maxButtonHeight = 16;
        public static final int Toolbar_navigationContentDescription = 21;
        public static final int Toolbar_navigationIcon = 20;
        public static final int Toolbar_popupTheme = 8;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 10;
        public static final int Toolbar_theme = 17;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMarginBottom = 15;
        public static final int Toolbar_titleMarginEnd = 13;
        public static final int Toolbar_titleMarginStart = 12;
        public static final int Toolbar_titleMarginTop = 14;
        public static final int Toolbar_titleMargins = 11;
        public static final int Toolbar_titleTextAppearance = 9;
        public static final int[] View;
        public static final int[] ViewStubCompat;
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 0;
        public static final int View_paddingEnd = 2;
        public static final int View_paddingStart = 1;
        public static final int[] WalletFragmentOptions;
        public static final int WalletFragmentOptions_appTheme = 0;
        public static final int WalletFragmentOptions_environment = 1;
        public static final int WalletFragmentOptions_fragmentMode = 3;
        public static final int WalletFragmentOptions_fragmentStyle = 2;
        public static final int[] WalletFragmentStyle;
        public static final int WalletFragmentStyle_buyButtonAppearance = 3;
        public static final int WalletFragmentStyle_buyButtonHeight = 0;
        public static final int WalletFragmentStyle_buyButtonText = 2;
        public static final int WalletFragmentStyle_buyButtonWidth = 1;
        public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
        public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
        public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
        public static final int[] WalletImButtonBar;
        public static final int WalletImButtonBar_capitalizeButtonText = 0;
        public static final int[] WalletImFormEditText;
        public static final int WalletImFormEditText_required = 4;
        public static final int WalletImFormEditText_requiredErrorString = 3;
        public static final int WalletImFormEditText_validateWhenNotVisible = 5;
        public static final int WalletImFormEditText_validatorErrorString = 1;
        public static final int WalletImFormEditText_validatorRegexp = 2;
        public static final int WalletImFormEditText_validatorType = 0;
        public static final int[] WalletImInfoMessageTextView;
        public static final int WalletImInfoMessageTextView_inlineExpandLabel = 0;
        public static final int[] WalletImMaxWidthView;
        public static final int WalletImMaxWidthView_maxWidth = 0;
        public static final int[] WarmWelcomeCard;
        public static final int WarmWelcomeCard_supports_dynamic_title_top_padding = 0;

        static {
            ActionBar = new int[]{R.attr.height, R.attr.title, R.attr.navigationMode, R.attr.displayOptions, R.attr.subtitle, R.attr.titleTextStyle, R.attr.subtitleTextStyle, R.attr.icon, R.attr.logo, R.attr.divider, R.attr.background, R.attr.backgroundStacked, R.attr.backgroundSplit, R.attr.customNavigationLayout, R.attr.homeLayout, R.attr.progressBarStyle, R.attr.indeterminateProgressStyle, R.attr.progressBarPadding, R.attr.itemPadding, R.attr.hideOnContentScroll, R.attr.contentInsetStart, R.attr.contentInsetEnd, R.attr.contentInsetLeft, R.attr.contentInsetRight, R.attr.elevation, R.attr.popupTheme, R.attr.homeAsUpIndicator};
            int[] iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = 16842931;
            ActionBarLayout = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[WalletImButtonBar_capitalizeButtonText];
            ActionMode = new int[]{R.attr.height, R.attr.titleTextStyle, R.attr.subtitleTextStyle, R.attr.background, R.attr.backgroundSplit, R.attr.closeItemLayout};
            ActivityChooserView = new int[]{R.attr.initialActivityCount, R.attr.expandActivityOverflowButtonDrawable};
            AdsAttrs = new int[]{R.attr.adSize, R.attr.adSizes, R.attr.adUnitId};
            AppDataSearch = new int[WalletImButtonBar_capitalizeButtonText];
            BindingFrameLayout = new int[]{R.attr.bind__isOwnedByParent, R.attr.bind__supportsAnimationCapture};
            BindingLinearLayout = new int[]{R.attr.bind__isOwnedByParent, R.attr.bind__supportsAnimationCapture};
            BindingRelativeLayout = new int[]{R.attr.bind__isOwnedByParent, R.attr.bind__supportsAnimationCapture};
            BoundImageView = new int[]{R.attr.bindImageUri, R.attr.bindDrawable};
            BoundTextView = new int[]{R.attr.bind__editModeText, R.attr.bindText, R.attr.bindTextColor, R.attr.bindDrawableStart, R.attr.bindDrawableEnd};
            BoundView = new int[]{R.attr.bindBackground, R.attr.bindContentDescription, R.attr.bindEnabled, R.attr.bindInvisibility, R.attr.bindMinHeight, R.attr.bindOnClickListener, R.attr.bindPaddingTop, R.attr.bindTransitionName, R.attr.bindVisibility};
            BucketRow = new int[]{R.attr.same_child_height, R.attr.same_child_width};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.checkableChildId;
            CheckableLinearLayout = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.textAllCaps;
            CompatTextView = iArr;
            ContentFrame = new int[]{R.attr.content, R.attr.contentId};
            Corpus = new int[]{R.attr.corpusId, R.attr.corpusVersion, R.attr.contentProviderUri, R.attr.trimmable, R.attr.schemaOrgType};
            DetailsColumnLayout = new int[]{R.attr.has_leading_gap, R.attr.leading_hero_section_id};
            DetailsSectionStack = new int[]{R.attr.separator_inset, R.attr.show_trailing_separator};
            DetailsTextBlock = new int[]{R.attr.regular_style_xmargin, R.attr.corpus_style_xmargin};
            DownloadStatusView = new int[]{R.attr.playDownloadArcInset, R.attr.playDownloadArcWidth, R.attr.playDownloadArcColorOnline, R.attr.playDownloadArcColorOffline, R.attr.playDownloadArcColorPress, R.attr.playDownloadArcColorDownload, R.attr.playDownloadArcMinPercent, R.attr.playDownloadPressDrawable, R.attr.playDownloadDownloadDrawable, R.attr.playDownloadFinishDrawable};
            DrawerArrowToggle = new int[]{R.attr.color, R.attr.spinBars, R.attr.drawableSize, R.attr.gapBetweenBars, R.attr.topBottomBarArrowSize, R.attr.middleBarArrowSize, R.attr.barSize, R.attr.thickness};
            FeatureParam = new int[]{R.attr.paramName, R.attr.paramValue};
            FifeImageView = new int[]{R.attr.fixed_bounds, R.attr.is_avatar, R.attr.is_avatar_no_ring, R.attr.zoom, R.attr.fade_in_after_load, R.attr.request_scale_factor};
            FlowLayoutManager_Layout = new int[]{R.attr.layout_flmWidth, R.attr.layout_flmHeight, R.attr.layout_flmGridInsetStart, R.attr.layout_flmGridInsetEnd, R.attr.layout_flmMaxGridWidth, R.attr.layout_flmGridColumnCount, R.attr.layout_flmGridMinCellSize, R.attr.layout_flmMargin, R.attr.layout_flmMarginTop, R.attr.layout_flmMarginStart, R.attr.layout_flmMarginEnd, R.attr.layout_flmMarginBottom, R.attr.layout_flmMarginTopForFirstLine, R.attr.layout_flmMarginBottomForLastLine, R.attr.layout_flmVAlign, R.attr.layout_flmFlow, R.attr.layout_flmFlowInsetTop, R.attr.layout_flmFlowInsetStart, R.attr.layout_flmFlowInsetEnd, R.attr.layout_flmFlowInsetBottom, R.attr.layout_flmFlowWidth, R.attr.layout_flmFlowHeight, R.attr.layout_flmLineWrap};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.layout_flmStyle;
            FlowLayoutManager_Layout_Style = iArr;
            GlobalSearch = new int[]{R.attr.searchEnabled, R.attr.searchLabel, R.attr.settingsDescription, R.attr.defaultIntentAction, R.attr.defaultIntentData, R.attr.defaultIntentActivity};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.allowShortcuts;
            GlobalSearchCorpus = iArr;
            GlobalSearchSection = new int[]{R.attr.sectionType, R.attr.sectionContent};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.full_screen_on;
            HeroGraphicView = iArr;
            HistogramTable = new int[]{R.attr.labels_on, R.attr.bar_height, R.attr.max_bar_width, R.attr.bar_margin};
            HistogramView = new int[]{R.attr.needs_height_correction, R.attr.shows_bottom_separator};
            IMECorpus = new int[]{R.attr.inputEnabled, R.attr.sourceClass, R.attr.userInputTag, R.attr.userInputSection, R.attr.userInputValue, R.attr.toAddressesSection};
            LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, R.attr.divider, R.attr.measureWithLargestChild, R.attr.showDividers, R.attr.dividerPadding};
            LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
            ListPopupWindow = new int[]{16843436, 16843437};
            LoadingImageView = new int[]{R.attr.imageAspectRatioAdjust, R.attr.imageAspectRatio, R.attr.circleCrop};
            MapAttrs = new int[]{R.attr.mapType, R.attr.cameraBearing, R.attr.cameraTargetLat, R.attr.cameraTargetLng, R.attr.cameraTilt, R.attr.cameraZoom, R.attr.liteMode, R.attr.uiCompass, R.attr.uiRotateGestures, R.attr.uiScrollGestures, R.attr.uiTiltGestures, R.attr.uiZoomControls, R.attr.uiZoomGestures, R.attr.useViewLifecycle, R.attr.zOrderOnTop, R.attr.uiMapToolbar};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.max_size_layout_height;
            MaxSizeLayoutHeight = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.max_width;
            MaxWidthView = iArr;
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, R.attr.showAsAction, R.attr.actionLayout, R.attr.actionViewClass, R.attr.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, R.attr.preserveIconSpacing};
            PlayActionButton = new int[]{R.attr.action_style, R.attr.draw_as_label, R.attr.use_all_caps_in_label_mode, R.attr.action_xpadding, R.attr.action_top_padding, R.attr.action_bottom_padding, R.attr.local_priority};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.primary_avatar_size;
            PlayAvatarPack = iArr;
            PlayCardBaseView = new int[]{R.attr.card_show_inline_creator_badge, R.attr.card_supports_subtitle_and_rating, R.attr.card_text_only_snippet_margin_left, R.attr.card_avatar_snippet_margin_left, R.attr.card_owned_status_rendering_type};
            PlayCardClusterViewContent = new int[]{R.attr.card_content_padding_top, R.attr.card_content_padding_bottom};
            PlayCardClusterViewHeader = new int[]{R.attr.min_header_height, R.attr.header_xpadding};
            PlayCardThumbnail = new int[]{R.attr.thumbnail_id, R.attr.app_thumbnail_padding, R.attr.person_thumbnail_padding};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.featured_card_layout_type;
            PlayCardViewFeatured = iArr;
            PlayCardViewGroup = new int[]{R.attr.playCardBackgroundColor, R.attr.playCardCornerRadius, R.attr.playCardElevation, R.attr.playCardInset, R.attr.playCardClipToOutline};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.is_flat;
            PlayCirclesButton = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.playSpacing;
            PlayEduCardButtonPanel = iArr;
            PlayImageView = new int[]{R.attr.fixed_bounds, R.attr.is_avatar, R.attr.zoom};
            PlaySeparatorLayout = new int[]{R.attr.separator_padding_top, R.attr.separator_padding_bottom, R.attr.separator_padding_left, R.attr.separator_padding_right};
            PlayTextView = new int[]{R.attr.allowsCompactLineSpacing, R.attr.lastLineOverdrawColor, R.attr.lastLineOverdrawHint, R.attr.lastLineOverdrawHintColor, R.attr.lastLineOverdrawAllCaps, R.attr.decoration_position};
            PopupWindow = new int[]{16843126, R.attr.overlapAnchor};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.state_above_anchor;
            PopupWindowBackgroundState = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.proportion;
            ProportionalOuterFrame = iArr;
            SearchView = new int[]{16842970, 16843039, 16843296, 16843364, R.attr.layout, R.attr.iconifiedByDefault, R.attr.queryHint, R.attr.closeIcon, R.attr.goIcon, R.attr.searchIcon, R.attr.voiceIcon, R.attr.commitIcon, R.attr.suggestionRowLayout, R.attr.queryBackground, R.attr.submitBackground};
            Section = new int[]{R.attr.sectionId, R.attr.sectionFormat, R.attr.noIndex, R.attr.sectionWeight, R.attr.indexPrefixes, R.attr.subsectionSeparator, R.attr.schemaOrgProperty};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.featureType;
            SectionFeature = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.separator_position;
            SeparatorLinearLayout = iArr;
            SetupWizardIllustration = new int[]{R.attr.collapsable, R.attr.aspectRatio};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.flexibleChildId;
            SingleLineContainer = iArr;
            Spinner = new int[]{16842927, 16842964, 16843125, 16843126, 16843362, 16843436, 16843437, R.attr.prompt, R.attr.spinnerMode, R.attr.popupPromptView, R.attr.disableChildrenWhenDisabled};
            StarRatingBar = new int[]{R.attr.rating, R.attr.range, R.attr.star_height, R.attr.star_color, R.attr.star_bg_color, R.attr.gap};
            SwitchCompat = new int[]{16843044, 16843045, 16843074, R.attr.track, R.attr.thumbTextPadding, R.attr.switchTextAppearance, R.attr.switchMinWidth, R.attr.switchPadding, R.attr.splitTrack, R.attr.showText};
            SwitchCompatTextAppearance = new int[]{16842901, 16842904, R.attr.textAllCaps};
            Theme = new int[]{16842839, 16842926, R.attr.windowActionBar, R.attr.windowActionBarOverlay, R.attr.windowActionModeOverlay, R.attr.windowFixedWidthMajor, R.attr.windowFixedHeightMinor, R.attr.windowFixedWidthMinor, R.attr.windowFixedHeightMajor, R.attr.actionBarTabStyle, R.attr.actionBarTabBarStyle, R.attr.actionBarTabTextStyle, R.attr.actionOverflowButtonStyle, R.attr.actionOverflowMenuStyle, R.attr.actionBarPopupTheme, R.attr.actionBarStyle, R.attr.actionBarSplitStyle, R.attr.actionBarTheme, R.attr.actionBarWidgetTheme, R.attr.actionBarSize, R.attr.actionBarDivider, R.attr.actionBarItemBackground, R.attr.actionMenuTextAppearance, R.attr.actionMenuTextColor, R.attr.actionModeStyle, R.attr.actionModeCloseButtonStyle, R.attr.actionModeBackground, R.attr.actionModeSplitBackground, R.attr.actionModeCloseDrawable, R.attr.actionModeCutDrawable, R.attr.actionModeCopyDrawable, R.attr.actionModePasteDrawable, R.attr.actionModeSelectAllDrawable, R.attr.actionModeShareDrawable, R.attr.actionModeFindDrawable, R.attr.actionModeWebSearchDrawable, R.attr.actionModePopupWindowStyle, R.attr.textAppearanceLargePopupMenu, R.attr.textAppearanceSmallPopupMenu, R.attr.actionDropDownStyle, R.attr.dropdownListPreferredItemHeight, R.attr.spinnerStyle, R.attr.spinnerDropDownItemStyle, R.attr.homeAsUpIndicator, R.attr.actionButtonStyle, R.attr.buttonBarStyle, R.attr.buttonBarButtonStyle, R.attr.selectableItemBackground, R.attr.selectableItemBackgroundBorderless, R.attr.dividerVertical, R.attr.dividerHorizontal, R.attr.activityChooserViewStyle, R.attr.toolbarStyle, R.attr.toolbarNavigationButtonStyle, R.attr.popupMenuStyle, R.attr.popupWindowStyle, R.attr.editTextColor, R.attr.editTextBackground, R.attr.switchStyle, R.attr.textAppearanceSearchResultTitle, R.attr.textAppearanceSearchResultSubtitle, R.attr.textColorSearchUrl, R.attr.searchViewStyle, R.attr.listPreferredItemHeight, R.attr.listPreferredItemHeightSmall, R.attr.listPreferredItemHeightLarge, R.attr.listPreferredItemPaddingLeft, R.attr.listPreferredItemPaddingRight, R.attr.dropDownListViewStyle, R.attr.listPopupWindowStyle, R.attr.textAppearanceListItem, R.attr.textAppearanceListItemSmall, R.attr.panelBackground, R.attr.panelMenuListWidth, R.attr.panelMenuListTheme, R.attr.listChoiceBackgroundIndicator, R.attr.colorPrimary, R.attr.colorPrimaryDark, R.attr.colorAccent, R.attr.colorControlNormal, R.attr.colorControlActivated, R.attr.colorControlHighlight, R.attr.colorButtonNormal, R.attr.colorSwitchThumbNormal};
            Toolbar = new int[]{16842927, 16843072, R.attr.title, R.attr.subtitle, R.attr.contentInsetStart, R.attr.contentInsetEnd, R.attr.contentInsetLeft, R.attr.contentInsetRight, R.attr.popupTheme, R.attr.titleTextAppearance, R.attr.subtitleTextAppearance, R.attr.titleMargins, R.attr.titleMarginStart, R.attr.titleMarginEnd, R.attr.titleMarginTop, R.attr.titleMarginBottom, R.attr.maxButtonHeight, R.attr.theme, R.attr.collapseIcon, R.attr.collapseContentDescription, R.attr.navigationIcon, R.attr.navigationContentDescription};
            View = new int[]{16842970, R.attr.paddingStart, R.attr.paddingEnd};
            ViewStubCompat = new int[]{16842960, 16842994, 16842995};
            WalletFragmentOptions = new int[]{R.attr.appTheme, R.attr.environment, R.attr.fragmentStyle, R.attr.fragmentMode};
            WalletFragmentStyle = new int[]{R.attr.buyButtonHeight, R.attr.buyButtonWidth, R.attr.buyButtonText, R.attr.buyButtonAppearance, R.attr.maskedWalletDetailsTextAppearance, R.attr.maskedWalletDetailsHeaderTextAppearance, R.attr.maskedWalletDetailsBackground, R.attr.maskedWalletDetailsButtonTextAppearance, R.attr.maskedWalletDetailsButtonBackground, R.attr.maskedWalletDetailsLogoTextColor, R.attr.maskedWalletDetailsLogoImageType};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.capitalizeButtonText;
            WalletImButtonBar = iArr;
            WalletImFormEditText = new int[]{R.attr.validatorType, R.attr.validatorErrorString, R.attr.validatorRegexp, R.attr.requiredErrorString, R.attr.required, R.attr.validateWhenNotVisible};
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.inlineExpandLabel;
            WalletImInfoMessageTextView = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.maxWidth;
            WalletImMaxWidthView = iArr;
            iArr = new int[WalletImFormEditText_validatorErrorString];
            iArr[WalletImButtonBar_capitalizeButtonText] = R.attr.supports_dynamic_title_top_padding;
            WarmWelcomeCard = iArr;
        }
    }
}
